import test from 'node:test';import assert from 'node:assert/strict';import{createHash}from'node:crypto';import{readFileSync}from'node:fs';import{mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{DatabaseSync}from'node:sqlite';
const origin='http://localhost:5173',api='http://localhost:8787/v1/fastfold/human/',hash=s=>createHash('sha256').update(s).digest('hex');
test('native SQLite DO six authenticated humans, persisted reconnect and actual no-request timeout alarm',{skip:!process.env.WORKERD_MODULE},async t=>{
 const{Miniflare}=await import(process.env.WORKERD_MODULE);const{build}=await import('../../frontend/node_modules/esbuild/lib/main.js');const dir=await mkdtemp(join(tmpdir(),'human-do-'));let mf;
 try{const bundle=await build({entryPoints:[new URL('../src/worker.ts',import.meta.url).pathname],bundle:true,write:false,platform:'browser',format:'esm',external:['cloudflare:workers'],logLevel:'silent'});
 const vars={FASTFOLD_ENABLED:'true',AUTH_ENABLED:'true',AUTH_LOCAL_DEV:'true',AUTH_APP_URL:origin,ALLOWED_ORIGIN:origin,GOOGLE_REDIRECT_URI:'http://localhost:8787/v1/account/google/callback',AUTH_RATE_LIMIT_KEY:'synthetic-only'};
 const options={cf:false,telemetry:{enabled:false},resourcePersistencePath:join(dir,'storage'),workers:[{config:{name:'human-local-test',compatibilityDate:'2026-09-22',env:{...Object.fromEntries(Object.entries(vars).map(([k,value])=>[k,{type:'text',value}])),DB:{type:'d1',id:'human-test-db'},FASTFOLD_RUNTIME:{type:'durable-object',worker:'human-local-test',exportName:'FastFoldRuntime'}},exports:{FastFoldRuntime:{type:'durable-object',storage:'sqlite'}},manifest:{mainModule:'worker.mjs',modulesRoot:'/',modules:{'worker.mjs':{type:'esm',contents:bundle.outputFiles[0].text}}}}}]};
 mf=new Miniflare(options);await mf.ready;let db=await mf.getD1Database('DB');const schema=new DatabaseSync(':memory:');for(const name of ['0007_accounts.sql','0011_human_ranked.sql'])schema.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));for(const row of schema.prepare('SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY rowid').all())await db.prepare(row.sql).run();schema.close();
 const tokens=[];for(let i=0;i<6;i++){tokens.push(hash('human-native-'+i));await db.prepare('INSERT INTO account_users VALUES(?,?,?,?)').bind('U'+i,'subject'+i,'synthetic@example.invalid',Date.now()).run();await db.prepare('INSERT INTO account_sessions VALUES(?,?,?)').bind(hash(tokens[i]),'U'+i,Math.floor(Date.now()/1000)+3600).run();}
 const call=async(i,path,body,status=200)=>{const res=await mf.dispatchFetch(api+path,{method:body?'POST':'GET',headers:{origin,cookie:'reysonai-dev-session='+tokens[i],...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const out=await res.json();assert.equal(res.status,status,JSON.stringify(out));return out;};const state=async i=>(await call(i,'profile')).state;const control=async(i,path,extra={})=>call(i,path,{version:(await state(i)).version,actionId:crypto.randomUUID(),...extra});
 for(let i=0;i<5;i++)await control(i,'join',{consent:true});assert.equal((await state(0)).match,undefined);await control(5,'join',{consent:true});for(let i=0;i<6;i++)await control(i,'accept',{reservationId:(await state(i)).reservation.id});let m=(await state(0)).match;assert.equal(m.participants.length,6);assert.deepEqual(Object.keys(m.hand.holeCards),['UTG']);assert.equal(m.hand.board.length,0);
 await mf.dispose();mf=new Miniflare(options);await mf.ready;db=await mf.getD1Database('DB');assert.deepEqual((await state(0)).match.hand.holeCards,m.hand.holeCards);
 // Shorten only this ephemeral test's turn deadline; a real DO alarm, not GET sweep,
 // must update the private engine while all clients remain silent.
 await db.prepare('UPDATE human_rank_tables SET expires_at=? WHERE id=?').bind(Date.now()+350,m.id).run();await state(0);await new Promise(r=>setTimeout(r,1100));const row=await db.prepare('SELECT version,private_json FROM human_rank_tables WHERE id=?').bind(m.id).first();assert.ok(row.version>m.version);const hidden=JSON.parse(row.private_json);assert.equal(hidden.hand.log[0].action,'fold');assert.equal(hidden.hand.turn,1);
 const csrf=await mf.dispatchFetch(api+'leave',{method:'POST',headers:{origin:'https://evil.invalid',cookie:'reysonai-dev-session='+tokens[1],'content-type':'application/json'},body:'{}'});assert.equal(csrf.status,403);t.diagnostic('Native workerd binding + real persistent alarm PASS; no production CPU claim.');
 }finally{if(mf)await mf.dispose();await rm(dir,{recursive:true,force:true})}
});
