// Agent baseline for the play-style dashboard: the same per-hand statistics the human gets
// (agent-stats.ts), measured on agents-only hands at every seat. Reads the local postflop
// candidates; a missing one is checked down, like at the table.
//   node scripts/agent/baseline.mjs [hands]  → src/agent/agent-baseline.json
import { writeFileSync } from "node:fs";
import { dataset } from "../../src/estimated/datasets.ts";
import { loadInputs } from "../postflop-ai/inputs.mjs";
import { loadCandidate, loadLaterCandidate } from "../postflop-ai/generate.mjs";
import { playHand } from "../../src/agent/hand.ts";
import { createAgent, makePostflopKit } from "../../src/agent/policy.ts";
import { handRecord, summarizeAgentHands } from "../../src/agent/agent-stats.ts";
import { POSITIONS } from "../../src/agent/preflop.ts";

const hands = Number(process.argv[2] ?? 1500);
const datasets = Object.fromEntries(["opening-ranges", "preflop-ranges", "three-bet-responses", "four-bet-responses", "limp-responses"].map(name => [name, dataset(name)]));
const kits = new Map();
let missing = 0;
const postflop = id => {
  if (!kits.has(id)) {
    let kit = null;
    try { const inputs = loadInputs(id); const candidate = loadCandidate(inputs); kit = makePostflopKit(id, datasets, candidate, loadLaterCandidate(inputs, candidate)); } catch { kit = null; }
    if (!kit) missing++;
    kits.set(id, kit);
  }
  return kits.get(id);
};
const agents = createAgent();
const records = [];
for (let i = 0; i < hands; i++) {
  const result = playHand({ seed: `baseline-${i}`, human: null, agents, postflop });
  for (const pos of POSITIONS) records.push(handRecord(result, "baseline", pos, 0));
  if ((i + 1) % 250 === 0) process.stderr.write(`${i + 1}/${hands}\n`);
}
const s = summarizeAgentHands(records);
const round = value => value == null ? null : Math.round(value * 1000) / 1000;
const out = { kind: "ai_estimate_not_gto", note: "Agents-only hands, every seat, balanced Reyson policy. Generated by scripts/agent/baseline.mjs.",
  generated: new Date().toISOString().slice(0, 10), hands, seatHands: records.length, missingPostflopSpots: missing,
  vpip: round(s.vpip), pfr: round(s.pfr), threeBet: round(s.threeBet), foldToThreeBet: round(s.foldToThreeBet),
  wtsd: round(s.wtsd), wsd: round(s.wsd), af: round(s.af), foldToBet: round(s.foldToBet) };
writeFileSync(new URL("../../src/agent/agent-baseline.json", import.meta.url), JSON.stringify(out, null, 2) + "\n");
console.log(out);
