export type SiteLocale = "en" | "ja";

export const en = {
  title: "Solvea — Poker strategy, made playable",
  description: "Solvea turns complex poker strategy into ranges you can understand, remember, and use. Explore AI-estimated preflop ranges and clear explanations.",
  navigation: [{ label: "Why Solvea", href: "#why" }, { label: "How it works", href: "#how" }, { label: "AI Solution", href: "#solution" }, { label: "Pricing", href: "#pricing" }],
  common: { home: "Solvea home", try: "Try Solvea", soon: "SOON", comingSoon: "Coming soon", signIn: "Sign in", signInHint: "Accounts are not available yet", menuOpen: "Open menu", menuClose: "Close menu", skip: "Skip to content", raise: "Raise", call: "Call", fold: "Fold", planned: "PLANNED" },
  preview: { explorer: "/ RANGE EXPLORER", currentSpot: "CURRENT SPOT", cash: "6-Max Cash", open: "BTN Open", response: "BB vs BTN", preflop: "PREFLOP", spotLabel: "Preview spot", matrixLabel: "13 by 13 starting hand matrix", scrollLabel: "range, horizontally scrollable on small screens", handRange: "HAND RANGE", selectedHand: "SELECTED HAND", suited: "SUITED", offsuit: "OFFSUIT", pair: "POCKET PAIR", why: "WHY THIS HAND?", k7s: "K7s is suited and playable after the flop. In this BTN opening estimate, it is raised every time.", other: (spot: string, hand: string, action: string, value: number) => `In this saved ${spot} range, ${hand} is ${action} ${value}% of the time. Open the app for the full hand-level explanation.`, explore: "Explore this range", saved: "SAVED AI ESTIMATE", notGto: "Not a GTO solution", spotOpening: "BTN opening", spotResponse: "BB response", actionPast: { raise: "raised", call: "called", fold: "folded" } },
  hero: { eyebrow: "THE NEW WAY TO LEARN POKER STRATEGY", title1: "Less solving.", title2: "More playing.", lead1: "AI-powered poker ranges made to be", leadEmphasis: "understood, remembered, and played.", lead2: "No endless trees. Just the strategy you can use.", secondary: "See how it works", proof1: "PRE-FLOP, MADE HUMAN", proof2: "EXPLORE A REAL RANGE", product: "01 / THE PRODUCT", clickHand: "Click any hand to explore", bottom: "STRATEGY THAT MAKES SENSE", scroll: "SCROLL TO EXPLORE" },
  problem: { eyebrow: "THE PROBLEM", title1: "Powerful tools.", title2: "Too much to carry.", description: "Solvers are extraordinary for deep study. But most players don't need to memorize every branch and frequency to make better decisions at the table.", items: [{ number: "01", title: "Hundreds of branches", detail: "The right answer can disappear inside a game tree." }, { number: "02", title: "Fractional decisions", detail: "47% raise. 38% call. 15% fold. Then what?" }, { number: "03", title: "Not built for recall", detail: "Useful theory is only useful if you can use it live." }], thesis1: "You don't have to study like a solver", thesis2: "to think like a stronger player." },
  how: { eyebrow: "A BETTER WAY IN", title1: "From spot to strategy", title2: "in three simple moves.", description: "No solver setup. No deciphering charts. Pick a situation and start learning.", steps: [{ number: "01 / CHOOSE", title: "Choose your spot.", description: "Select the game, stack, and positions. That's enough to get going." }, { number: "02 / SEE", title: "See your range.", description: "A clear 13 × 13 map turns a complex strategy into a usable decision." }, { number: "03 / UNDERSTAND", title: "Ask why.", description: "Go beyond memorizing cells. See the thinking behind the action." }], yourSpot: "YOUR SPOT", versusBb: "vs BB", range: "BTN OPEN RANGE", whyK7s: "WHY K7s?", exampleReason: "“It's suited, plays well after the flop, and fits this BTN opening range.”", understand: "UNDERSTAND THE REASON" },
  simple: { eyebrow: "CLARITY IS A FEATURE", title1: "Less to memorize.", title2: "More to use.", description: "Start with the clearest decision. Look at the detail when you want it. Solvea meets you where you are—not where a solver expects you to be.", link: "Explore simple mode", mixed: "ILLUSTRATIVE MIXED STRATEGY", illustration: "Concept illustration; not a competitor's data.", simpleView: "SOLVEA · SIMPLE VIEW", oneDecision: "One clear action to start with. Detail when you need it." },
  solution: { eyebrow: "THE SOLVEA APPROACH", title1: "Not GTO.", title2: "Not guesswork.", title3: "An AI Solution.", description: "Solvea's current preflop ranges are AI estimates, checked for structural consistency and explained in human language. They are not solver output or a claim of mathematical optimality.", link: "See the current preview", trust: "HOW WE BUILD TRUST", stages: [{ title: "Generate", detail: "AI-estimated strategy" }, { title: "Validate", detail: "Structural checks" }, { title: "Explain", detail: "Reasons you can learn from" }, { title: "Refine together", detail: "AI review pipeline · planned" }], built: "Built for humans.", edge: "Not for solving every edge case." },
  adaptive: { eyebrow: "THE NEXT CHAPTER", title1: "Your table", title2: "isn't always", title3: "GTO.", description: "One day, ask Solvea about the people and patterns at your table. The goal: strategy that adapts to your context while staying easy to understand.", promptLabel: "TRY A CONCEPT PROMPT", note: "Interactive concept preview only. Natural-language range adjustment is not available in the current app.", tableContext: "SOLVEA / TABLE CONTEXT", concept: "CONCEPT", personal: "A MORE PERSONAL STRATEGY", preview: "PREVIEW", future: "Future feature preview, not a live AI response", input: "Ask anything about your range...", examples: [{ prompt: "Everyone at my table calls too much.", response: "I'd favor hands that retain value when called and reconsider the weakest opens." }, { prompt: "They almost never 3-bet.", response: "We could revisit the opens that normally suffer against frequent 3-bets." }, { prompt: "Make this easier to remember.", response: "Let's group similar hands into a smaller number of clear decisions." }] },
  learning: { card: "HAND DETAIL / BTN OPEN", explanation: "AI EXPLANATION", cardReason: "Suited hands like K7s can make strong flushes. On the button, this estimate opens it as a raise.", questions: ["Why not fold?", "Compare with K6s", "What changes at 50BB?"], eyebrow: "LEARN AS YOU PLAY", title1: "Don't just memorize.", title2: "Understand.", description: "Every decision has a reason. Tap a hand and see the logic behind the range—in plain language, right beside the chart.", feature1: "Click a hand", feature1Detail: "Go from a colored square to a clear action.", feature2: "See the reasoning", feature2Detail: "Build intuition instead of memorizing a pattern.", note: "Suggested follow-up questions shown are a future conversational experience." },
  levels: { eyebrow: "YOUR JOURNEY", title1: "Built for the player", title2: "you're becoming.", description: "Choose the amount of detail that helps you grow. You can always look deeper.", tabLabel: "Learning level", items: [{ label: "Beginner", headline: "Find your first clear answer.", body: "A simplified display shows the main action first, keeping the cognitive load low." }, { label: "Standard", headline: "See the full picture.", body: "Inspect the underlying action frequencies and learn where decisions mix." }, { label: "Advanced", headline: "Go deeper when you need to.", body: "More advanced training is on the roadmap. The current app offers simple and standard views." }], mode: "MODE", link: "Explore the current app", sameHand: "SAME HAND. THE RIGHT AMOUNT OF DETAIL.", advanced: "ADVANCED · PLANNED", standard: "STANDARD VIEW", simple: "SIMPLE VIEW", future: "Additional training tools are not yet available." },
  comparison: { eyebrow: "DIFFERENT TOOLS, DIFFERENT JOBS", title1: "The right tool depends", title2: "on what you're here to do.", description: "Traditional solvers and Solvea serve different ways of learning. Neither needs to replace the other.", solver: "Traditional GTO Solver", solverDescription: "For deep theoretical study and detailed control.", solverFeatures: ["Large game trees", "Precise mixed frequencies", "Maximum configuration", "Advanced analysis"], solverTag: "STUDY THE THEORY", solveaDescription: "For making practical strategy easier to grasp.", solveaFeatures: ["Approachable AI-estimated ranges", "Plain-language explanations", "Fast decisions", "Designed for learning"], solveaTag: "PLAY WITH CLARITY" },
  pricing: { eyebrow: "PRICING", title1: "Start learning.", title2: "Keep growing.", description: "Explore the current preview for free. A paid plan is an early proposal, not a live subscription.", note: "The ¥680 Plus price and all paid features are provisional. No billing or account system is available yet.", plans: [{ name: "Free", price: "¥0", cadence: "forever", description: "Start seeing the game more clearly.", features: ["Explore available preflop ranges", "Hand-by-hand explanations", "Simple and standard display modes"], action: "Try the preview", href: "/app" as string | null, status: "Available preview" }, { name: "Plus", price: "¥680", cadence: "/ month · proposed", description: "A deeper practice space, when it's ready.", features: ["Expanded learning tools", "More guided training", "Future adaptive features"], action: "Coming soon", href: null as string | null, status: "Planned · pricing may change" }] },
  final: { eyebrow: "YOUR NEXT HAND STARTS HERE", title1: "Play smarter.", title2: "Study lighter.", description: "Simple ranges. Clear explanations. Built for real players.", action: "Start with Solvea", note: "Free preview · No account required" },
  footer: { tagline: "Poker strategy, made playable.", product: "PRODUCT", how: "How it works", open: "Open the app", explore: "EXPLORE", pricing: "Pricing", about: "About Solvea", privacy: "Privacy · coming soon", terms: "Terms · coming soon", disclaimer: "Solvea provides poker strategy and educational information. AI Solutions are estimates and are not guaranteed to be mathematically optimal or equivalent to GTO solutions. Please play responsibly.", madeFor: "MADE FOR THE THINKING PLAYER" },
};

export type SiteCopy = typeof en;
