import type { SiteCopy } from "./content";

export const ja: SiteCopy = {
  title: "EvionAI — 実戦で使えるポーカー戦略",
  description: "AIが推定したプリフロップレンジを読みやすい13×13の表で確認し、ハンドごとの理由を知り、ドリルで身につける。学習のための推定であり、GTOソルバーではありません。",
  common: { home: "EvionAI ホーム", open: "アプリを開く", menuOpen: "メニューを開く", menuClose: "メニューを閉じる", menuLabel: "メインメニュー", skip: "本文へスキップ", language: "EN", languageLabel: "Switch to English", raise: "レイズ", threeBet: "3ベット", call: "コール", fold: "フォールド", available: "提供中", planned: "予定", experimental: "試験運用" },
  nav: [
    { label: "使い方", href: "#how" },
    { label: "トレーニング", href: "#drill" },
    { label: "分析", href: "#analysis" },
    { label: "比較", href: "#compare" },
    { label: "料金", href: "#pricing" },
  ],
  hero: { title1: "複雑な戦略を、", title2: "使える判断に。", lead: "EvionAIは、AIが推定したポーカーのレンジを一目で読める表にし、ハンドごとの理由をやさしい言葉で説明します。テーブルに座ったときにも思い出せる形で。", primary: "アプリを開く", secondary: "使い方を見る", note: "無料プレビュー · アカウント不要 · 6-maxキャッシュ 100BB" },
  preview: { spotLabel: "プレビューする局面", open: "BTN オープン", response: "BB vs BTN", displayLabel: "表示モード", simpleMode: "シンプル", standardMode: "スタンダード", matrixLabel: "13×13 スターティングハンド表", scrollLabel: "の表。狭い画面では横にスクロールできます", selectedHand: "選択中のハンド", suited: "スーテッド", offsuit: "オフスート", pair: "ペア", frequencyLabel: "アクション頻度", why: "理由", k7s: "K7s はスーテッドで、フロップ以降も戦いやすいハンドです。このBTNオープンの推定では、常にレイズします。", simpleOther: (spot: string, hand: string, action: string) => `保存済みの${spot}レンジでは、${hand} の主なアクションは${action}です。ハンドごとの詳しい説明はアプリで確認できます。`, other: (spot: string, hand: string, action: string, value: number) => `保存済みの${spot}レンジでは、${hand} を ${value}% の頻度で${action}します。ハンドごとの詳しい説明はアプリで確認できます。`, explore: "アプリでこのレンジを見る", saved: "保存済みのAI推定", notGto: "GTOソリューションではありません", spotOpening: "BTNオープン", spotResponse: "BBの応答", actionPast: { raise: "レイズ", threeBet: "3ベット", call: "コール", fold: "フォールド" }, touring: "自動でハンドを紹介中。セルをクリックすると操作できます。", manual: "ハンドをクリックして確認できます。" },
  how: {
    title1: "局面から理由まで、", title2: "3ステップで。",
    steps: [
      { title: "局面を決める。", body: "席ごとにアクションをたどります。BTNまでフォールド、2.5BBのオープン、BBの番。" },
      { title: "色で読む。", body: "169ハンドそれぞれの主なアクションを、一色で表示します。まずはそこから。混ざる判断を見たくなったら、スタンダード表示へ切り替えます。" },
      { title: "理由を知る。", body: "ハンドをタップすると、正確なアクション頻度と、その裏付けとなる事実を言葉で確認できます。数字の壁ではなく。" },
    ],
    toAct: "アクション待ち", openSize: "レイズ 2.5BB", pot: "ポット 4BB", combos: "のハンド",
    whyHand: "A5s · BB vs BTN", whyNote: "Aのブロッカーとホイール（A〜5のストレート）の可能性を持つスーテッドAです。BTNのオープンレンジには勝率52.3%と優位で、続けてくる相手にも43.3%とほぼ互角です。相手が3bet（12BB）に54.9%降りる分を合わせると、コールより3bet（12BB）のほうが得になります。一部はコールに回し、コールするレンジにも強いハンドを残します。",
  },
  drill: { title1: "10秒で、", title2: "ひとつの判断を。", description: "BTNまでフォールドで回ってきました。オープンしますか？ 答えたあと、保存済みの推定が同じハンドをどう打つかを確認できます。", question: "BTNのアクション", tableFold: "Fold", stakes: "キャッシュ · 6-max · 100BB", pot: "ポット", raise: "レイズ 2.5BB", fold: "フォールド", next: "次へ", match: "推定と同じ判断", differ: "推定とは異なる判断", mixed: "混合のハンド", frequency: (value: number) => `推定でのこの選択の頻度 ${value}%`, score: (matched: number, played: number) => `${played}ハンド中 ${matched} 一致`, tableLabel: (hand: string) => `テーブル。BTNまでフォールドで、あなたのハンドは ${hand} です。`, note: "練習の判定は保存済みのAI推定との比較です。GTOソリューションや実戦の結果との比較ではありません。" },
  audience: {
    title1: "解くより、", title2: "上手くなりたい人へ。",
    items: [
      { level: "初心者", quote: "そもそも、どのハンドで参加すればいいの？", body: "シンプル表示で、各ハンドの主なアクションをまず一色で。よく出る局面から始められます。", gets: "シンプル表示 · よく出る局面から" },
      { level: "初中級者", quote: "チャートは覚えた。でも、そのアクションの理由が分からない。", body: "スタンダード表示で正確な頻度を確認し、ハンドごとにそのアクションを選ぶ理由を言葉で読めます。", gets: "スタンダード表示 · ハンドごとの理由" },
      { level: "費用を抑えたい人", quote: "ソルバーは高くて、手が出ない。", body: "いまのプレビューは無料。有料のソルバーツールに払わなくても、レンジ表、ハンドごとの理由、20問のドリル、ランク戦、分析ページで練習できます。", gets: "ドリル · ランク戦 · 分析" },
    ],
    views: ["シンプル表示", "ハンド詳細", "無料プレビュー"],
    freeList: ["保存済み局面のレンジ表", "ハンドごとの理由", "ドリルと振り返り", "プレー分析"],
    freeNote: "アカウント不要",
    note: "任意のゲームツリーで厳密なソルバー解を調べたいなら、ソルバー系アプリの方が適しています。",
  },
  ranked: {
    status: "近日公開", title1: "ランク戦で、", title2: "実力をレートに。",
    description: "全員が同じ条件で20問に挑みます。迷いようのないハンドではレートはほとんど動かず、混合のハンドほど大きく動きます。ブロンズからマスターまで駆け上がりましょう。",
    points: ["全局面から20問、標準の難易度", "ランク戦は1日3試合まで", "イロレーティング方式：難しいハンドほど重く評価", "週間・通算のランキング"],
    sample: "表示例", rank: "ランク", rating: "レート", peak: "最高", toNext: (points: number, tier: string) => `${tier}まであと${points}`, today: "本日の残り 2 / 3 試合", lastMatch: "前回の試合", matchLine: (correct: number, total: number) => `${total}問中 ${correct}問正解 · 正答率 ${Math.round(correct / total * 100)}%`,
    tiers: ["ブロンズ", "シルバー", "ゴールド", "プラチナ", "ダイヤモンド", "マスター"],
  },
  analysis: {
    title1: "自分のクセが、", title2: "数字で見える。",
    description: "練習の回答はすべて保存済みの推定と比べられます。EvionAIはそれを、プレイスタイルマップ、アクションの傾向、強みと弱点、次に練習すべきことにまとめます。",
    points: [
      { title: "プレイスタイルマップ", body: "あなたの選択がタイトかルースか、3ベットが多いか少ないかを位置で示します。" },
      { title: "アクションの傾向", body: "フォールド・オープン・コール・3ベットの頻度を、推定と比べて表示します。" },
      { title: "強みと弱点", body: "得意な局面と、間違えたハンドの復習リストが分かります。" },
      { title: "セッション履歴", body: "このブラウザーに保存されたドリルを、振り返ったり再開したりできます。" },
    ],
    note: "このブラウザーに保存された練習の回答から作ります。傾向は練習でのもので、実戦の結果ではありません。",
    sample: "表示例", score: "EvionAI Score", accuracy: "正答率", style: "プレイスタイル", styleValue: "TAG", recent: "直近10回答", answers: "回答",
    map: "プレイスタイルマップ", tight: "タイト", loose: "ルース", quadrants: ["TAG", "LAG", "タイト・パッシブ", "ルース・パッシブ"],
    tendencies: "推定と比べたアクションの選び方", actions: ["フォールド", "オープン", "コール", "3ベット"],
    weak: "弱点", weakValue: "CO vs BTN · 3ベット", next: "次に練習", nextValue: "A5s · KTo · 76s",
  },
  compare: {
    title1: "ソルバーアプリとは、", title2: "役割が違う。",
    description: "GTO Wizard などのソルバー系GTOアプリは、厳密な理論の基準です。EvionAIは、その戦略を理解し、練習し続けるために作られています。",
    us: "EvionAI", them: "ソルバー系GTOアプリ", themNote: "例：GTO Wizard",
    rows: [
      { label: "表示するもの", us: "AIが推定したレンジ。推定と明記", them: "ソルバーが計算したGTO戦略" },
      { label: "説明の仕方", us: "ハンドごとの理由を、やさしい言葉で", them: "頻度やEVなど、数字が中心" },
      { label: "情報の細かさ", us: "レベルに合わせてシンプル・スタンダード・上級", them: "経験者向けに、すべてを詳細に" },
      { label: "練習", us: "ドリルと、レートを競うランク戦", them: "ソルバー解にもとづくトレーナー" },
      { label: "フィードバック", us: "プレイスタイルマップ、傾向、弱点", them: "ソルバーのプレーとの比較スコア" },
      { label: "精度", us: "実用的な近似。GTOではない", them: "解いたゲームの範囲で厳密" },
      { label: "向いている人", us: "習慣を作りたい初心者〜初中級者", them: "厳密な理論を研究したい人" },
    ],
    note: "アプローチの一般的な比較です。個々の製品の機能は異なり、変わることがあります。GTO Wizard は各権利者の商標であり、EvionAIとは関係ありません。",
  },
  pricing: { title1: "まずは無料で。", title2: "準備ができたら、その先へ。", description: "現在のプレビューは無料です。有料プランは初期の提案で、まだ提供していません。", note: "Plus の ¥680 という価格と有料機能はすべて仮案です。課金やアカウントの仕組みはまだありません。", plans: [{ name: "Free", price: "¥0", cadence: "ずっと無料", description: "現在のプレビューのすべて。", features: ["保存済みのプリフロップレンジとハンド詳細", "シンプル／スタンダード表示", "トレーナー、振り返り、プレー分析"], action: "アプリを開く", href: "/app" as string | null, status: "提供中" }, { name: "Plus", price: "¥680", cadence: "/ 月 · 提案中", description: "準備ができたら、より深い練習の場を。", features: ["学習ツールの拡充", "ガイドつきトレーニングの追加", "卓に合わせた今後の機能"], action: "今後提供予定", href: null as string | null, status: "予定 · 価格は変わる可能性があります" }] },
  faq: {
    title: "よくある質問に、率直に。",
    items: [
      { question: "これはGTOですか？", answer: "いいえ。EvionAIが表示するのは、学習のためのAI推定レンジです。ソルバーの出力ではなく、数学的な最適性も保証しません。" },
      { question: "GTO Wizard との違いは？", answer: "GTO Wizard などは、ソルバーが計算した戦略を示す厳密な理論の基準です。EvionAIは学習のためのAI推定を、解説、ドリル、ランク戦、練習の分析とあわせて提供します。詳しくは上の比較をご覧ください。" },
      { question: "どのゲームに対応していますか？", answer: "6-maxキャッシュゲーム、100BB、アンティなしです。オープンは2.5BB（SBは3.5BB）。保存データのない局面は「未収録」と表示し、推測では埋めません。" },
      { question: "アカウントは必要ですか？", answer: "不要です。プロフィールと練習履歴はこのブラウザーに保存されます。アカウント機能は予定しています。" },
      { question: "ポストフロップにも対応していますか？", answer: "対応するヘッズアップの流れで、フロップからリバーまでを試験的に提供しています。アプリ内でも試験運用と明示しています。" },
      { question: "料金はかかりますか？", answer: "現在のプレビューは無料です。Plus プランを提案していますが、まだ提供しておらず、価格も変わる可能性があります。" },
    ],
  },
  final: { title1: "次のセッションは、", title2: "ひとつのハンドから。", description: "アプリを開いて、局面を選び、ハンドをタップするだけ。", action: "EvionAI を開く", note: "無料プレビュー · アカウント不要" },
  footer: { tagline: "ポーカー戦略を、使える形に。", product: "プロダクト", open: "アプリを開く", how: "使い方", drill: "トレーニング", analysis: "分析", compare: "比較", pricing: "料金", faq: "よくある質問", legal: "規約", privacy: "プライバシー · 準備中", terms: "利用規約 · 準備中", disclaimer: "EvionAIはポーカーの戦略と学習のための情報を提供します。AIソリューションは推定であり、数学的な最適性やGTOソリューションとの同等性は保証されません。節度をもってお楽しみください。" },
};
