import type { SiteCopy } from "./content";

export const es: SiteCopy = {
  title: "ReysonAI — No te limites a jugar. Entiende el porqué.",
  description: "Consulta rangos preflop estimados por IA en una tabla clara de 13×13, entiende por qué se juega así cada mano y practica. Una estimación para aprender, no un solver GTO.",
  common: { home: "Inicio de ReysonAI", open: "Abrir la app", menuOpen: "Abrir menú", menuClose: "Cerrar menú", menuLabel: "Navegación principal", skip: "Saltar al contenido", language: "Idioma", languageLabel: "Seleccionar idioma", you: "TÚ", raise: "Subir", threeBet: "3bet", call: "Igualar", fold: "Retirarse", available: "Disponible", planned: "Previsto", experimental: "Experimental" },
  nav: [
    { label: "Cómo funciona", href: "#how" },
    { label: "Entrenamiento", href: "#drill" },
    { label: "Análisis", href: "#analysis" },
    { label: "Comparativa", href: "#compare" },
    { label: "Precios", href: "#pricing" },
  ],
  hero: { title1: "Don't just play.", title2: "Understand why.", lead: "ReysonAI te muestra qué hacer con cada mano y explica el porqué con palabras sencillas. Cuando entiendes la razón, recuerdas la decisión al sentarte a la mesa.", primary: "Abrir la app", secondary: "Ver cómo funciona", note: "Vista previa gratuita · Sin cuenta · Cash de 6 jugadores, 100BB" },
  preview: { simpleMode: "Simple", matrixLabel: "Tabla de manos iniciales de 13 por 13", scrollLabel: "con desplazamiento horizontal en pantallas pequeñas", selectedHand: "Mano seleccionada", suited: "Del mismo palo", offsuit: "De distinto palo", pair: "Pareja", frequencyLabel: "Frecuencias de acción", why: "Por qué", k7s: "K7s es del mismo palo y tiene buena jugabilidad después del flop. En esta estimación de apertura desde BTN, se sube siempre.", other: (spot: string, hand: string, action: string, value: number) => `En este rango guardado de ${spot}, con ${hand} se elige ${action} el ${value}% de las veces. Abre la app para ver la explicación completa de la mano.`, explore: "Explorar este rango en la app", saved: "Estimación de IA guardada", notGto: "No es una solución GTO", spotOpening: "apertura de BTN", spotResponse: "respuesta de BB", actionPast: { raise: "subir", threeBet: "hacer 3bet", call: "igualar", fold: "retirarse" }, pauseTour: "Pausar recorrido de manos", resumeTour: "Reanudar recorrido de manos", touring: "Recorrido automático. Pulsa cualquier casilla para explorar.", manual: "Pulsa una mano para verla." },
  how: {
    title1: "De la situación al porqué,", title2: "en tres pasos.",
    steps: [
      { title: "Define la situación.", body: "Recorre las acciones asiento por asiento. Todos se retiran hasta el botón, que abre a 2.5BB, y le toca a la ciega grande." },
      { title: "Lee los colores.", body: "Cada una de las 169 manos muestra su acción principal con un color sólido. Empieza por ahí. Cambia a la vista Estándar para ver las decisiones mixtas." },
      { title: "Entiende el porqué.", body: "Pulsa una mano para ver su mezcla exacta de acciones y los datos que la explican, con palabras claras en lugar de un muro de números." },
    ],
    toAct: "Le toca actuar", openSize: "Subir a 2.5BB", pot: "Bote de 4BB", combos: "de las manos",
    whyHand: "A5s · BB vs BTN", whyNote: "Un as del mismo palo que bloquea otros ases y puede formar la escalera A–5. Tiene un 52.3% de equity contra el rango de apertura del botón y un 43.3%, cerca de la igualdad, contra las manos que continúan. Al contar el 54.9% de veces que el botón se retira ante un 3bet a 12BB, hacer 3bet supera a igualar. Algunas combinaciones siguen igualando para conservar manos fuertes también en ese rango.",
  },
  drill: { title1: "Diez segundos.", title2: "Una decisión.", description: "Todos se retiran y te toca en el botón. ¿Abres? Responde y comprueba qué hace la estimación guardada con esa misma mano.", question: "Le toca a BTN", tableFold: "Fold", stakes: "Cash · 6 jugadores · 100BB", pot: "Bote", raise: "Subir a 2.5BB", fold: "Retirarse", next: "Siguiente", match: "Coincide con la estimación", differ: "La estimación es distinta", mixed: "Mano de estrategia mixta", frequency: (value: number) => `La estimación elige esto el ${value}% de las veces`, score: (matched: number, played: number) => `${matched} de ${played} coinciden`, tableLabel: (hand: string) => `Mesa. Todos se retiran hasta el botón y tienes ${hand}.`, note: "La práctica compara tu respuesta con la estimación de IA guardada, no con una solución GTO ni con resultados reales." },
  audience: {
    title1: "Para quienes prefieren", title2: "jugar y aprender.",
    items: [
      { level: "Principiante", quote: "¿Qué manos debería jugar?", body: "La vista Simple muestra primero la acción principal de cada mano, empezando por las situaciones más habituales.", gets: "Vista Simple · situaciones habituales primero" },
      { level: "De principiante a intermedio", quote: "Memoricé la tabla. Aún no entiendo las mezclas.", body: "La vista Estándar muestra las frecuencias exactas y cada mano explica por qué combina acciones.", gets: "Vista Estándar · razones mano a mano" },
      { level: "Presupuesto ajustado", quote: "Los solvers son demasiado caros para mí.", body: "La vista previa es gratuita. Practica con tablas de rangos, explicaciones de cada mano, ejercicios de veinte preguntas, partidas clasificatorias y análisis, sin pagar una suscripción a un solver.", gets: "Ejercicios · clasificatorias · análisis" },
    ],
    views: ["Vista Simple", "Detalle de mano", "Vista previa gratuita"],
    freeList: ["Tablas de rangos para situaciones guardadas", "Explicaciones de cada mano", "Ejercicios y revisión de sesiones", "Análisis de juego"],
    freeNote: "Sin cuenta",
    note: "¿Quieres estudiar soluciones exactas de árboles de juego personalizados? Para eso, una app basada en un solver es más adecuada.",
  },
  ranked: {
    status: "Próximamente", title1: "Partidas clasificatorias.", title2: "Gánate tu puntuación.",
    description: "Veinte preguntas con las mismas condiciones para todos. Las manos claras apenas cambian tu puntuación; las mixtas tienen el mayor impacto. Sube de Bronce a Maestro.",
    points: ["20 preguntas de todas las situaciones, dificultad estándar", "Tres partidas clasificatorias al día", "Puntuación tipo Elo: las manos difíciles pesan más", "Clasificación semanal e histórica"],
    sample: "Ejemplo", rank: "Rango", rating: "Puntuación", peak: "Máxima", toNext: (points: number, tier: string) => `${points} puntos para ${tier}`, today: "Quedan 2 / 3 partidas hoy", lastMatch: "Última partida", matchLine: (correct: number, total: number) => `${correct} / ${total} correctas · ${Math.round(correct / total * 100)}% de acierto`,
    tiers: ["Bronce", "Plata", "Oro", "Platino", "Diamante", "Maestro"],
  },
  agent: {
    status: "Beta", title1: "Mesa de Agents.", title2: "Aplica lo aprendido.",
    description: "Siéntate en una mesa de 6 jugadores con cinco Agents que siguen la estimación de Reyson AI. Aplica los rangos estudiados a las manos que recibas.",
    points: ["Cada Agent sigue Reyson solver (estimación de IA)", "Cash de 100BB, con resultados en puntos", "Tu estilo de juego según tus últimas 1,000 manos", "Después del flop, solo uno contra uno por ahora (beta)"],
    sample: "Ejemplo",
  },
  analysis: {
    title1: "Descubre cómo", title2: "juegas de verdad.",
    description: "Cada respuesta de práctica se compara con la estimación para que tus hábitos se reflejen en números.",
    points: ["Estilo: cerrado o amplio, pasivo o agresivo", "Dónde te retiras, igualas o haces 3bet de más o de menos", "Puntos débiles y próximos ejercicios"],
    note: "A partir de tus respuestas de práctica, no de resultados reales.",
    sample: "Ejemplo", score: "ReysonAI Score", accuracy: "Acierto", style: "Estilo de juego", styleValue: "TAG", recent: "últimas 10 respuestas", answers: "respuestas",
    map: "Mapa de estilo", tight: "Cerrado", loose: "Amplio", quadrants: ["TAG", "LAG", "Cerrado-pasivo", "Amplio-pasivo"],
    tendencies: "Acciones frente a la estimación", actions: ["Retirarse", "Abrir", "Igualar", "3bet"],
    weak: "Punto débil", weakValue: "CO vs BTN · 3bet", next: "Practicar después", nextValue: "A5s · KTo · 76s",
  },
  compare: {
    title1: "Una forma distinta", title2: "de aprender.",
    description: "Las apps GTO basadas en solvers, como GTO Wizard, son la referencia para la teoría exacta. ReysonAI está diseñado para ayudarte a aprender una estrategia y seguir practicándola.",
    us: "ReysonAI", them: "Apps GTO con solver", themNote: "p. ej., GTO Wizard",
    rows: [
      { label: "Qué ves", us: "Rangos estimados por IA, identificados como estimaciones", them: "Estrategias GTO calculadas por un solver" },
      { label: "Cómo se explica", us: "Razones claras para cada mano", them: "Primero los números: frecuencias y EV" },
      { label: "Nivel de detalle", us: "Simple, Estándar o Avanzado, según tu nivel", them: "Todo el detalle, para jugadores con experiencia" },
      { label: "Práctica", us: "Ejercicios y clasificatorias con puntuación", them: "Entrenadores basados en soluciones del solver" },
      { label: "Comentarios", us: "Mapa de estilo, tendencias y puntos débiles", them: "Puntuación frente al juego del solver" },
      { label: "Precisión", us: "Una aproximación práctica, no GTO", them: "Exacta dentro del juego resuelto" },
      { label: "Para quién", us: "Principiantes e intermedios que crean hábitos", them: "Jugadores que estudian teoría exacta" },
    ],
    note: "Comparación general de enfoques; cada producto es distinto y puede cambiar. GTO Wizard es una marca de su titular y no tiene afiliación con ReysonAI.",
  },
  pricing: { title1: "Empieza gratis.", title2: "Plus por unos US$0.12 al día.", description: "", note: "Plus aún no está disponible; las funciones de pago y la facturación no están activas.", plans: [{ name: "Free", price: "$0", cadence: "para siempre", description: "Todo lo incluido en la vista previa actual.", features: ["Rangos preflop guardados y detalles de manos", "Vistas Simple y Estándar", "Entrenador, revisión de sesiones y análisis"], action: "Abrir la app", href: "/analyze/ranges" as string | null, status: "Disponible" }, { name: "Plus", price: "$3.70", cadence: "/ mes · USD aprox.", description: "Un espacio de práctica más completo, cuando esté listo.", features: ["Más herramientas de aprendizaje", "Más entrenamiento guiado", "Futuras funciones adaptadas a la mesa"], action: "Más adelante", href: null as string | null, status: "Previsto" }] },
  faq: {
    title: "Preguntas con respuestas claras.",
    items: [
      { question: "¿Esto es GTO?", answer: "No. ReysonAI muestra rangos estimados por IA para aprender. No son resultados de un solver ni se garantiza que sean matemáticamente óptimos." },
      { question: "¿En qué se diferencia de GTO Wizard?", answer: "GTO Wizard y apps similares muestran estrategias calculadas por un solver y son la referencia para la teoría exacta. ReysonAI ofrece estimaciones de IA para aprender, con explicaciones, ejercicios, clasificatorias y análisis de tu práctica. Consulta la comparativa anterior." },
      { question: "¿Qué juegos incluye?", answer: "Cash de 6 jugadores con 100BB y sin ante. Las aperturas son a 2.5BB, o a 3.5BB desde la ciega pequeña. Las situaciones sin datos guardados se indican como no registradas, nunca se inventan." },
      { question: "¿Necesito una cuenta?", answer: "No. Tu perfil y tu historial de práctica se guardan en este navegador. Las cuentas están previstas." },
      { question: "¿Incluye juego postflop?", answer: "Una prueba experimental cubre las líneas compatibles de uno contra uno desde el flop hasta el river. La app lo identifica como experimental." },
      { question: "¿Cuánto cuesta?", answer: "La vista previa actual es gratuita. Plus costará unos US$3.70 al mes, unos US$0.12 al día calculados sobre 30 días, pero aún no está disponible. El importe en USD es una conversión aproximada y puede cambiar con el tipo de cambio." },
    ],
  },
  final: { title1: "Tu próxima sesión", title2: "empieza con una mano.", description: "Abre la app, elige una situación y pulsa una mano.", action: "Abrir ReysonAI", note: "Vista previa gratuita · Sin cuenta" },
  footer: { tagline: "Don't just play. Understand why.", product: "Producto", open: "Abrir la app", how: "Cómo funciona", drill: "Entrenamiento", analysis: "Análisis", compare: "Comparativa", pricing: "Precios", faq: "Preguntas frecuentes", legal: "Legal", privacy: "Privacidad · próximamente", terms: "Condiciones · próximamente", disclaimer: "ReysonAI ofrece información educativa y de estrategia de póquer. Las soluciones de IA son estimaciones y no se garantiza que sean matemáticamente óptimas ni equivalentes a soluciones GTO. Juega de forma responsable." },
};
