import type { SiteCopy } from "./content";

export const ja: SiteCopy = {
  title: "EvionAI — ポーカー戦略を、実戦で使える形に",
  description: "EvionAIは複雑なポーカー戦略を、理解しやすく覚えやすいAI推定レンジに。プリフロップの戦略とハンドごとの理由を学べます。",
  navigation: [{ label: "EvionAIとは", href: "#why" }, { label: "使い方", href: "#how" }, { label: "AI Solution", href: "#solution" }, { label: "料金", href: "#pricing" }],
  common: { home: "EvionAI ホーム", try: "EvionAIを試す", soon: "準備中", comingSoon: "近日公開", signIn: "ログイン", signInHint: "アカウント機能はまだ利用できません", menuOpen: "メニューを開く", menuClose: "メニューを閉じる", skip: "本文へ移動", raise: "レイズ", call: "コール", fold: "フォールド", planned: "開発予定" },
  preview: { explorer: "/ レンジを見る", currentSpot: "選択中の局面", cash: "6人卓 キャッシュ", open: "BTN オープン", response: "BB 対 BTN", preflop: "プリフロップ", spotLabel: "プレビューする局面", displayLabel: "表示モード", simpleMode: "シンプル", standardMode: "スタンダード", frequencyLabel: "アクション頻度", matrixLabel: "13×13のスターティングハンド表", scrollLabel: "レンジ。狭い画面では横にスクロールできます", handRange: "ハンドレンジ", selectedHand: "選択中のハンド", suited: "スーテッド", offsuit: "オフスート", pair: "ポケットペア", why: "この判断の理由", k7s: "K7sはスーテッドで、フロップ以降もプレイしやすいハンド。このBTNオープンの推定レンジでは、毎回レイズします。", simpleOther: (spot, hand, action) => `保存済みの${spot}レンジでは、${hand}の主なアクションは${action}です。詳しいハンド別の理由はアプリで確認できます。`, other: (spot, hand, action, value) => `保存済みの${spot}レンジでは、${hand}は${value}%の頻度で${action}します。詳しいハンド別の理由はアプリで確認できます。`, explore: "このレンジを詳しく見る", saved: "保存済みAI推定", notGto: "GTOソリューションではありません", spotOpening: "BTNオープン", spotResponse: "BB対BTN", actionPast: { raise: "レイズ", call: "コール", fold: "フォールド" } },
  hero: { eyebrow: "AIで学ぶ、実戦のポーカー戦略", title1: "複雑な理論を。", title2: "使える戦略に。", lead1: "AIがポーカーのレンジを、", leadEmphasis: "理解しやすく、覚えやすく、実戦で使いやすく。", lead2: "膨大なゲームツリーを読み解く前に、まず必要な判断から。", secondary: "使い方を見る", proof1: "人が使えるプリフロップ戦略", proof2: "実際のレンジを体験", product: "01 / プロダクト体験", clickHand: "ハンドを選んで確認", bottom: "分かるから、使える戦略", scroll: "下へスクロール" },
  problem: { eyebrow: "課題", title1: "強力なツール。", title2: "でも、学ぶ量は膨大。", description: "ソルバーは理論を深く研究するための優れた道具です。ただ、実戦で判断を良くするために、すべての分岐や頻度を暗記する必要はありません。", items: [{ number: "01", title: "多すぎる分岐", detail: "知りたい判断が、巨大なゲームツリーに埋もれてしまう。" }, { number: "02", title: "細かな混合頻度", detail: "レイズ47%、コール38%、フォールド15%。実戦ではどう使う？" }, { number: "03", title: "覚えにくいチャート", detail: "テーブルで思い出せなければ、学んだ理論を活かせない。" }], thesis1: "ソルバーのように研究しなくても、", thesis2: "もっと良い判断は学べる。" },
  how: { eyebrow: "シンプルな使い方", title1: "局面を選んで、", title2: "戦略を理解する。", description: "複雑なソルバー設定は不要。局面を選べば、すぐに学び始められます。", steps: [{ number: "01 / 選ぶ", title: "局面を選ぶ。", description: "ゲーム、スタック、ポジションを選択。それだけで始められます。" }, { number: "02 / 見る", title: "レンジを見る。", description: "13×13の表で、複雑な戦略をひと目で確認。" }, { number: "03 / 理解する", title: "理由を知る。", description: "色を覚えるだけでなく、判断の背景まで理解できます。" }], yourSpot: "あなたの局面", versusBb: "対 BB", range: "BTNオープンレンジ", whyK7s: "なぜK7s？", exampleReason: "「スーテッドでフロップ後も扱いやすく、BTNのオープンレンジに入ります。」", understand: "判断の理由を知る" },
  simple: { eyebrow: "シンプルさも価値", title1: "暗記は少なく。", title2: "実戦ではもっと。", description: "まずは分かりやすい主なアクションから。詳しい頻度は、必要になったときに見ればいい。EvionAIはあなたの学び方に合わせます。", link: "シンプル表示を試す", mixed: "混合戦略の説明用例", illustration: "説明用の架空例です。競合製品の実データではありません。", simpleView: "EVIONAI · シンプル表示", oneDecision: "まず覚えるのは一つの判断。詳細は必要なときに。" },
  solution: { eyebrow: "EVIONAIの考え方", title1: "GTOではない。", title2: "勘だけでもない。", title3: "AI Solution。", description: "現在のプリフロップレンジは、構造的な整合性を確認したAI推定です。理由も人が理解できる言葉で示します。ソルバーの計算結果や、数学的な最適解ではありません。", link: "現在のプレビューを見る", trust: "品質への取り組み", stages: [{ title: "生成", detail: "AIによる戦略推定" }, { title: "検証", detail: "構造と整合性の確認" }, { title: "説明", detail: "学びにつながる理由" }, { title: "改善", detail: "AIレビュー工程は開発予定" }], built: "人が使うために。", edge: "すべての微差を解くためではなく。" },
  adaptive: { eyebrow: "次のステップ", title1: "あなたの卓は、", title2: "いつも", title3: "GTOどおりじゃない。", description: "将来的には、卓のプレイヤーや傾向を自然な言葉でEvionAIに伝えられるように。状況に合わせながら、理解しやすさを保つ戦略を目指します。", promptLabel: "構想中の質問例", note: "これは操作できるコンセプト表示です。自然言語によるレンジ調整は現在のアプリでは利用できません。", tableContext: "EVIONAI / 卓の傾向", concept: "構想", personal: "卓に合った戦略へ", preview: "表示例", future: "将来機能の表示例です。実際のAI応答ではありません", input: "レンジについて質問する…", examples: [{ prompt: "この卓はコールが多い", response: "コールされた後も価値を保ちやすいハンドを重視し、弱いオープンを見直す方向が考えられます。" }, { prompt: "相手がほとんど3betしない", response: "頻繁な3betに弱いハンドも含め、オープンレンジを見直せるかもしれません。" }, { prompt: "もっと覚えやすくして", response: "似たハンドをまとめて、覚える判断の数を減らしてみましょう。" }] },
  learning: { card: "ハンド詳細 / BTNオープン", explanation: "AIの説明", cardReason: "K7sはスーテッドでフラッシュを狙えます。このBTNオープンの推定ではレイズを選びます。", questions: ["なぜフォールドしない？", "K6sと比べる", "50BBなら変わる？"], eyebrow: "プレイしながら学ぶ", title1: "丸暗記より、", title2: "理解しよう。", description: "すべての判断には理由があります。ハンドを選べば、レンジの背景をチャートの隣で分かりやすく確認できます。", feature1: "ハンドを選ぶ", feature1Detail: "色のついたマスから、具体的なアクションへ。", feature2: "理由を読む", feature2Detail: "パターンの暗記ではなく、判断の直感を育てる。", note: "表示している追加質問は、将来の対話機能のイメージです。" },
  levels: { eyebrow: "あなたの成長に合わせて", title1: "今の自分から、", title2: "次のレベルへ。", description: "学びやすい情報量を選べます。必要になれば、いつでも詳しく。", tabLabel: "学習レベル", items: [{ label: "初級", headline: "まず、明確な一手から。", body: "主なアクションを優先して表示し、覚える負担を減らします。" }, { label: "中級", headline: "判断の全体像を見る。", body: "アクションの頻度を確認し、混合している場面も学べます。" }, { label: "上級", headline: "必要なときに、もっと深く。", body: "より高度な学習機能は開発予定です。現在のアプリではシンプル・スタンダード表示を利用できます。" }], mode: "モード", link: "現在のアプリを見る", sameHand: "同じハンド。学びに合った情報量。", advanced: "上級 · 開発予定", standard: "スタンダード表示", simple: "シンプル表示", future: "追加の学習機能はまだ利用できません。" },
  comparison: { eyebrow: "目的で選ぶツール", title1: "大切なのは、", title2: "何を学びたいか。", description: "従来のGTOソルバーとEvionAIは、異なる学び方のためのツールです。優劣ではなく、目的で選べます。", solver: "従来のGTOソルバー", solverDescription: "理論を深く研究し、細部まで分析したい人に。", solverFeatures: ["大規模なゲームツリー", "詳細な混合頻度", "豊富な設定項目", "高度な分析"], solverTag: "理論を深く研究する", solveaDescription: "実戦で使う戦略を、分かりやすく学びたい人に。", solveaFeatures: ["理解しやすいAI推定レンジ", "自然な言葉での説明", "素早い判断", "学習のための設計"], solveaTag: "明確な判断につなげる" },
  pricing: { eyebrow: "料金", title1: "まずは無料で。", title2: "学びを深めよう。", description: "現在のプレビューは無料で試せます。有料プランは初期案であり、まだ購入できません。", note: "Plusの月額680円と記載機能はすべて仮案です。現在、課金・アカウント機能はありません。", plans: [{ name: "Free", price: "¥0", cadence: "無料", description: "まずはレンジを見て、判断を理解する。", features: ["公開済みプリフロップレンジ", "ハンドごとの説明", "シンプル・スタンダード表示"], action: "無料プレビューを試す", href: "/app", status: "現在利用できるプレビュー" }, { name: "Plus", price: "¥680", cadence: "/ 月 · 仮価格", description: "より深く学べる場へ。準備を進めています。", features: ["学習ツールの拡充", "より充実したトレーニング", "将来の卓別調整機能"], action: "準備中", href: null, status: "開発予定 · 価格は変更の可能性あり" }] },
  final: { eyebrow: "次のハンドから始めよう", title1: "もっと明確に。", title2: "もっと強く。", description: "シンプルなレンジ。分かりやすい理由。実戦で使うプレイヤーのために。", action: "EvionAIを始める", note: "無料プレビュー · アカウント不要" },
  footer: { tagline: "ポーカー戦略を、実戦で使える形に。", product: "プロダクト", how: "使い方", open: "アプリを開く", explore: "サイト", pricing: "料金", about: "EvionAIについて", privacy: "プライバシー · 準備中", terms: "利用規約 · 準備中", disclaimer: "EvionAIはポーカー戦略に関する教育情報を提供します。AI Solutionは推定であり、数学的な最適性やGTOソリューションとの同等性を保証するものではありません。責任を持ってプレイしてください。", madeFor: "考えながらプレイする人へ" },
};
