/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.test.jsonc --include-runtime=false` (hash: 3513bba5614d731f463146a361ddc09d)
interface __BaseEnv_Env {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	MCP_ENABLED: "false";
	MCP_ACCESS_MODE: "authenticated_free";
	MCP_ORIGIN: "https://api.example.invalid";
	MCP_ALLOWED_ORIGINS: "https://app.example.invalid";
	AUTH_ENABLED: "true";
	AUTH_APP_URL: "https://app.example.invalid";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_ENABLED" | "MCP_ACCESS_MODE" | "MCP_ORIGIN" | "MCP_ALLOWED_ORIGINS" | "AUTH_ENABLED" | "AUTH_APP_URL">> {}
}
