import { productLocale } from "../i18n.ts";
const COPY = {
  en: { unavailable: "Three-player strategy unavailable", detail: "This line has no approved, current saved three-player strategy. The hand cannot continue yet.", loading: "Reading the three-player AI estimate…", pick: "Choose three distinct flop cards.", invalid: "This board or action history is invalid.", retry: "Retry", check: "Check", fold: "Fold", call: "Call", bet: "Bet", raise: "Raise to", allin: "All-in", pot: "Pot", wins: "wins the pot", complete: "Betting complete", showdown: "Showdown", beta: "Beta · saved AI estimates", rule: "Three-player single-raised pots use their own approved saved AI estimates. Four-player and three-player squeeze/3bet pots remain unavailable.", blocked: "This call would reach a three-player line without an approved saved strategy, or an unsupported pot with four or more players.", failed: "The saved three-player strategy could not be verified. Retry or leave this table.", ended: "The three-player hand is paused; chips and session points have not been settled." },
  ja: { unavailable: "3人用方針は未収録です", detail: "この経路には、承認済みで現在の入力に一致する保存済み3人用方針がありません。まだハンドを続行できません。", loading: "3人用AI推定を読み込み中…", pick: "重複しない3枚のフロップカードを選んでください。", invalid: "ボードまたは行動履歴が不正です。", retry: "再試行", check: "チェック", fold: "フォールド", call: "コール", bet: "ベット", raise: "レイズ先", allin: "オールイン", pot: "ポット", wins: "がポットを獲得", complete: "このストリートの行動は終了", showdown: "ショーダウン", beta: "β版 · 保存済みAI推定", rule: "3人のシングルレイズドポットには承認済みの専用AI推定を使います。4人以上と、スクイーズ・3bet後の3人ポットは未対応です。", blocked: "このコールで、承認済みの保存方針がない3人経路か、未対応の4人以上のポットになります。", failed: "保存済み3人用方針を検証できませんでした。再試行するか、卓を退出してください。", ended: "3人ハンドは停止中です。チップとセッションポイントはまだ精算していません。" },
  "zh-CN": { unavailable: "三人策略尚不可用", detail: "此路线没有已批准且与当前输入一致的已保存三人策略。暂时无法继续这手牌。", loading: "正在读取三人AI估算…", pick: "请选择三张不重复的翻牌。", invalid: "公共牌或行动记录无效。", retry: "重试", check: "过牌", fold: "弃牌", call: "跟注", bet: "下注", raise: "加注至", allin: "全下", pot: "底池", wins: "赢得底池", complete: "本轮行动结束", showdown: "摊牌", beta: "测试版 · 已保存AI估算", rule: "三人单次加注底池使用独立且已批准的AI估算。四人以上以及挤压或3bet后的三人底池暂不可用。", blocked: "此跟注会进入尚无已批准策略的三人路线，或不支持的四人以上底池。", failed: "无法验证已保存的三人策略。请重试或离开牌桌。", ended: "三人牌局已暂停，筹码和本场积分尚未结算。" },
  es: { unavailable: "Estrategia de tres jugadores no disponible", detail: "Esta línea no tiene una estrategia guardada de tres jugadores aprobada y vigente. La mano aún no puede continuar.", loading: "Leyendo la estimación de IA para tres jugadores…", pick: "Elige tres cartas distintas para el flop.", invalid: "Las cartas o el historial de acciones no son válidos.", retry: "Reintentar", check: "Pasar", fold: "Retirarse", call: "Igualar", bet: "Apostar", raise: "Subir a", allin: "All-in", pot: "Bote", wins: "gana el bote", complete: "Apuestas de esta calle completas", showdown: "Mostrar cartas", beta: "Beta · estimaciones de IA guardadas", rule: "Los botes de tres jugadores con una sola subida usan estimaciones de IA propias y aprobadas. Los botes de cuatro jugadores y los de tres tras squeeze o 3bet siguen sin estar disponibles.", blocked: "Igualar aquí crea una línea de tres jugadores sin estrategia aprobada o un bote no admitido de cuatro o más jugadores.", failed: "No se pudo verificar la estrategia guardada para tres jugadores. Reintenta o sal de la mesa.", ended: "La mano de tres jugadores está pausada; las fichas y los puntos de la sesión aún no se han liquidado." },
};
export function mw3Copy(locale = productLocale()) { return COPY[locale as keyof typeof COPY] ?? COPY.en; }
export function mw3ActionLabel(group: { action: string; amountBb: number; toBb: number; allIn: boolean }, locale = productLocale()) {
  const t = mw3Copy(locale), n = (value: number) => Number(value.toFixed(2)).toString();
  if (group.action === "check" || group.action === "fold") return t[group.action];
  if (group.action === "call") return `${t.call} ${n(group.amountBb)}BB${group.allIn ? ` (${t.allin})` : ""}`;
  if (group.allIn) return `${t.allin} ${n(group.toBb)}BB`;
  if (group.action === "raise") return `${t.raise} ${n(group.toBb)}BB`;
  return `${t.bet} ${n(group.amountBb)}BB (${group.action.slice(3)}%)`;
}
