import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import { writeFileSync, unlinkSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';
import { createRoot } from 'react-dom/client';
import React, { act } from 'react';
import worker from '../../backend/src/index.ts';
import { humanRankFixture } from '../../backend/tests/fixtures/human-rank.mjs';

// Isolated in-memory authenticated integration. No real cookies, users, OAuth,
// production requests, auth bypass, persisted fixtures or deployed ranking.
const buildResult = await build({ stdin: { contents: 'export { TrainerPage } from "./src/trainer/TrainerPage.tsx"; export { refreshAccount } from "./src/account/session.ts";', resolveDir: process.cwd(), loader: 'tsx' }, bundle: true, write: false, platform: 'node', format: 'esm', external: ['react', 'react-dom', 'react-dom/client'], jsx: 'automatic', loader: { '.css': 'empty', '.png': 'dataurl', '.webp': 'dataurl' }, define: { 'import.meta.env': JSON.stringify({ DEV: true }), 'import.meta.url': JSON.stringify(new URL('../src/estimated/datasets.ts', import.meta.url).href) } });
const code = buildResult.outputFiles[0].text.replace(/from "(react(?:\/jsx-runtime)?|react-dom(?:\/client)?)"/g, (_, name) => `from "${import.meta.resolve(name)}"`);
const bundlePath = `/tmp/reyson-fastfold-app-test-${process.pid}.mjs`;
writeFileSync(bundlePath, code);
after(() => unlinkSync(bundlePath));
const { TrainerPage, refreshAccount } = await import(pathToFileURL(bundlePath).href);
test('actual Trainer uses six authenticated humans, unrated Agent waiting, server handoff and queue break',async()=>{
  const server=await humanRankFixture();Object.assign(server.env,{GOOGLE_CLIENT_ID:'ephemeral-test-only',GOOGLE_CLIENT_SECRET:'ephemeral-test-only'});
  const calls=[];const fetcher=async(url,options={})=>{calls.push({url,options});return worker.fetch(new Request(url,{...options,headers:{...options.headers,origin:'http://localhost:5173',cookie:`reysonai-dev-session=${server.tokens[0]}`}}),server.env);};
  const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost:5173/learn/trainer'});const previous={window:globalThis.window,document:globalThis.document,localStorage:globalThis.localStorage,fetch:globalThis.fetch,HTMLElement:globalThis.HTMLElement};Object.assign(globalThis,{window:dom.window,document:dom.window.document,localStorage:dom.window.localStorage,fetch:fetcher,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});dom.window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});dom.window.scrollTo=()=>{};dom.window.localStorage.setItem('reysonai:agent-speed','"fast"');
  let root=createRoot(dom.window.document.getElementById('root')),path='/learn/trainer';const nav=[];const props={profile:{nickname:'Test',level:'intermediate',updatedAt:new Date().toISOString()},onSectionChange(){},onNavigate(next,replace){nav.push({next,replace});path=next;render();}};const render=()=>root.render(React.createElement(TrainerPage,{...props,path}));
  const settle=async predicate=>{for(let i=0;i<150&&!predicate();i++)await act(async()=>new Promise(r=>setTimeout(r,100)));assert.ok(predicate(),'UI state did not settle');};const click=async selector=>{const b=dom.window.document.querySelector(selector);assert.ok(b,`Missing ${selector}`);await act(async()=>b.click());};
  try{
    await refreshAccount();await act(async()=>render());await settle(()=>dom.window.document.querySelector('.is-ranked .mode-primary')?.disabled === false);assert.equal(dom.window.document.querySelectorAll('.is-ranked .rank-ladder').length,0);assert.equal(dom.window.document.querySelectorAll('.is-ranked .ranked-current .rank-badge').length,1);assert.match(dom.window.document.querySelector('.is-ranked').textContent,/Six people/);await click('.is-ranked .mode-primary');await settle(()=>Boolean(dom.window.document.querySelector('.ff-intro input')));assert.equal(dom.window.document.querySelector('.agent-felt'),null);assert.equal(server.sqlite.prepare('SELECT COUNT(*) n FROM human_rank_tables').get().n,0);
    await click('.ff-intro input');await click('.ff-intro .setup-start');await settle(()=>Boolean(dom.window.document.querySelector('.game-controls-trigger')));await click('.game-controls-trigger');await settle(()=>Boolean(dom.window.document.querySelector('.ff-human-queue')));assert.match(dom.window.document.querySelector('.ff-human-queue').textContent,/1 \/ 6/);assert.equal((await server.state(0)).hands,0);assert.equal(server.sqlite.prepare('SELECT COUNT(*) n FROM human_rank_tables').get().n,0);
    for(let i=1;i<6;i++)await server.join(i);await act(async()=>window.dispatchEvent(new window.Event('focus')));await settle(()=>dom.window.document.body.textContent.includes('Six people reserved'));
    const first=await server.state(0);assert.equal(first.phase,'reserved');assert.equal(first.reservation.accepted,false);await click('.game-modal-header button');
    // Finish only the current real local Agent hand. The server reservation is accepted at
    // its genuine completion boundary, not by simulating any human actions/cards locally.
    if(!dom.window.document.querySelector('.agent-result')){await settle(()=>Boolean(dom.window.document.querySelector('.agent-act.tone-fold')) || Boolean(dom.window.document.querySelector('.agent-result')));if(dom.window.document.querySelector('.agent-act.tone-fold'))await click('.agent-act.tone-fold');}
    await click('.game-controls-trigger');await settle(()=>dom.window.document.body.textContent.includes('Accepted. Waiting'));assert.equal((await server.state(0)).reservation.accepted,true);assert.equal(dom.window.document.querySelector('.ff-actions'),null);
    for(let i=1;i<6;i++){const s=await server.state(i);await server.control(i,'accept',{reservationId:s.reservation.id});}await act(async()=>window.dispatchEvent(new window.Event('focus')));await settle(()=>Boolean(dom.window.document.querySelector('.ff-actions')));const human=await server.state(0);assert.equal(human.phase,'hand');assert.equal(dom.window.document.querySelectorAll('.agent-seat').length,6);assert.equal(dom.window.document.querySelectorAll('.agent-hole .is-back').length,10);assert.deepEqual(Object.keys(human.match.hand.holeCards),[human.match.participants[human.match.hero].position]);
    // The immediate loading block is not a resolved server-public profile.
    await click('.agent-profile-trigger');await settle(()=>dom.window.document.querySelector('.agent-profile-block')?.textContent.includes('Unknown'));assert.match(dom.window.document.querySelector('.agent-profile-block').textContent,/Unknown/);assert.ok(dom.window.document.querySelector('.agent-profile-block').closest('[role=dialog][aria-modal=true]'));assert.equal(dom.window.document.querySelector('.agent-side'),null);await click('.agent-profile-block button');
    await click('.ff-actions .tone-fold');await settle(()=>Boolean(dom.window.document.querySelector('.ff-human-wait .game-controls-trigger')));await click('.game-controls-trigger');assert.ok(dom.window.document.querySelector('.ff-human-queue'));await click('.game-modal-header button');assert.equal((await server.state(0)).phase,'queued');assert.equal(server.sqlite.prepare("SELECT status FROM human_rank_tables WHERE id=?").get(human.match.id).status,'active');
    await click('.ff-exit');await settle(()=>path==='/learn/trainer/ranked/waiting');const deadline=(await server.state(0)).breakExpiresAt;assert.ok(deadline);assert.match(dom.window.document.body.textContent,/not the old hand/);await act(async()=>root.unmount());root=createRoot(dom.window.document.getElementById('root'));await act(async()=>render());await settle(()=>Boolean(dom.window.document.querySelector('.ff-countdown')));assert.equal((await server.state(0)).breakExpiresAt,deadline);
    const resume=[...dom.window.document.querySelectorAll('button')].find(b=>b.textContent==='Resume');await act(async()=>resume.click());await settle(()=>path==='/learn/trainer/ranked/play');assert.equal((await server.state(0)).phase,'queued');await settle(()=>Boolean(dom.window.document.querySelector('.ff-exit')));await click('.ff-exit');await settle(()=>path==='/learn/trainer/ranked/waiting');
    // Ephemeral SQLite server-only deadline fixture, not a browser clock/auth override.
    server.sqlite.prepare("UPDATE human_rank_players SET break_until=? WHERE user_id='U0'").run(Date.now()-1);await act(async()=>window.dispatchEvent(new window.Event('focus')));await settle(()=>path==='/learn/trainer');assert.equal(nav.at(-1).replace,true);assert.equal((await server.state(0)).phase,'out');assert.ok(!path.includes('/agent/'));assert.ok(calls.every(c=>!String(c.url).includes('/v1/ranked/matches')&&!/\/v1\/fastfold\/(?:start|profile|action)$/.test(String(c.url))));assert.ok(!Object.keys(dom.window.localStorage).some(k=>/agent-hands/.test(k)));
  }finally{await act(async()=>root.unmount());dom.window.close();Object.assign(globalThis,previous);delete globalThis.IS_REACT_ACT_ENVIRONMENT;server.close();}
});
