import test from "node:test";
import assert from "node:assert/strict";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
const built = await build({stdin:{contents:'export {HumanRankArena} from "./src/trainer/HumanRankArena.tsx";',resolveDir:process.cwd(),loader:"tsx"},bundle:true,write:false,platform:"node",format:"esm",external:["react"],jsx:"automatic",loader:{".css":"empty"},define:{"import.meta.url":JSON.stringify(new URL("../src/estimated/datasets.ts",import.meta.url).href)},plugins:[{name:"test-agent-boundary",setup(b){b.onResolve({filter:/AgentTable\.tsx$/},()=>({path:"local-agent",namespace:"test"}));b.onLoad({filter:/.*/,namespace:"test"},()=>({contents:`import React from 'react';export function AgentTablePage(p){return <section data-testid="unrated-local-Agent"><header>{p.waitingHeader}<button disabled={p.exitDisabled} onClick={p.onExit}>Exit</button></header>{p.waitingSidebar}<button onClick={p.onHandBoundary}>Test: Agent hand ended</button></section>}`,loader:"tsx"}));}}]});
const code=built.outputFiles[0].text.replace(/from "(react(?:\/jsx-runtime)?)"/g,(_,name)=>`from "${import.meta.resolve(name)}"`);
const {HumanRankArena}=await import(`data:text/javascript;base64,${Buffer.from(code).toString("base64")}`);
const NOW=1700000000000;
const positions=["UTG","HJ","CO","BTN","SB","BB"];
const base=(phase="out",extra={})=>({enabled:true,season:"human-fastfold-v1",serverNow:NOW,publicName:"Player self",state:{phase,version:0,rating:1000,peak:1000,hands:0,netBb:0,bbPer100:null,provisional:true,uncertainty:null,recent:[],leaseExpiresAt:NOW+45000,queue:{humans:phase==="out"?0:1,required:6},...extra}});
const match=()=>({id:"server-table",version:4,hero:3,turnExpiresAt:NOW+30000,participants:positions.map((position,seat)=>({seat,position,player:{id:`public-${seat}`,name:`Anonymous Player ${seat} very long public name`,hands:2,rating:1000,style:"unknown"}})),hand:{id:"server-hand",status:"playing",street:"preflop",board:[],holeCards:{BTN:["As","Kd"]},seats:positions.map(position=>({position,stack:100,committed:0,bet:0,folded:false,allIn:false,departed:false})),pending:{seat:3,position:"BTN",street:"preflop",pot:1.5,toCall:1,options:[{key:"fold"},{key:"call"},{key:"raise_250",to:2.5},{key:"all_in",to:100}]},log:[]}});
async function harness(run,fetcher,ready=true,view="play",setup=()=>{}){
 const dom=new JSDOM('<div id="root"></div>',{url:"http://localhost/learn/trainer/ranked/play"});const before={window:globalThis.window,document:globalThis.document,fetch:globalThis.fetch,HTMLElement:globalThis.HTMLElement};Object.assign(globalThis,{window:dom.window,document:dom.window.document,fetch:fetcher,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
 setup(dom);
 const root=createRoot(dom.window.document.getElementById("root"));const nav=[],updates=[];const props={ready,view,onBack:()=>nav.push("library"),onWaiting:()=>nav.push("waiting"),onPlay:()=>nav.push("play"),onRanking(){},onProfile:p=>updates.push(p)};
 const click=async label=>{const b=[...dom.window.document.querySelectorAll("button")].find(b=>b.textContent===label);assert.ok(b,`missing ${label}`);await act(async()=>b.click());};
 try{await act(async()=>root.render(React.createElement(HumanRankArena,props)));await run({dom,root,props,nav,updates,click});}finally{await act(async()=>root.unmount());dom.window.close();Object.assign(globalThis,before);delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
}
const fetchProfile=p=>async url=>url.endsWith("/status")?Response.json({enabled:true,season:"human-fastfold-v1",mode:"six_verified_humans",requiredHumans:6,comparisonMode:"shadow",appliedPenalty:false}):Response.json(p);
test("human ranked fails closed for guest and legacy readiness; never resumes old Agent ranked",async()=>{
 let calls=0;await harness(({dom})=>assert.match(dom.window.document.body.textContent,/Sign in/),async()=>{calls++;throw Error();},false);assert.equal(calls,0);
 const urls=[];await harness(({dom})=>{assert.match(dom.window.document.body.textContent,/unavailable/);assert.equal(dom.window.document.querySelector(".agent-felt"),null);},async url=>{urls.push(url);return Response.json({enabled:true,season:"fastfold-v1"});});assert.equal(urls.length,1);assert.ok(urls[0].includes("/human/status"));
});
test("zero humans does not deal; explicit join uses server count and unrated Agent waiting",async()=>{
 const posts=[];await harness(async({dom,click,updates})=>{assert.equal(dom.window.document.querySelector(".agent-felt"),null);assert.equal(posts.length,0);assert.ok(dom.window.document.querySelector(".setup-start").disabled);await act(async()=>dom.window.document.querySelector("input").click());await click("Join human queue");assert.match(dom.window.document.body.textContent,/1 \/ 6/);assert.match(dom.window.document.body.textContent,/not rated or saved/);assert.ok(dom.window.document.querySelector('[data-testid="unrated-local-Agent"]'));assert.equal(updates.at(-1).state.hands,0);assert.equal(dom.window.document.querySelectorAll("[data-tier]").length,7);},async(url,opts)=>{if(opts?.method==="POST"){posts.push(JSON.parse(opts.body));return Response.json(base("queued"));}return fetchProfile(base())(url);});assert.equal(posts[0].consent,true);assert.ok(posts[0].actionId);
});
test("six-person reservation accepts only after local hand boundary, then renders only server legal actions",async()=>{
 const reservation={id:"reservation",expiresAt:NOW+60000,accepted:false,acceptedHumans:0};const posts=[];
 await harness(async({dom,click})=>{assert.equal(posts.length,0);assert.match(dom.window.document.body.textContent,/after this Agent hand finishes/);await click("Test: Agent hand ended");assert.equal(posts[0].reservationId,"reservation");assert.equal(dom.window.document.querySelectorAll(".agent-seat").length,6);assert.equal(dom.window.document.querySelectorAll(".agent-hole .is-back").length,10);await click("Raise 2.5 bb");assert.equal(posts[1].action,"raise_250");assert.equal(posts[1].version,4);assert.equal(posts[1].tableId,"server-table");},async(url,opts)=>{if(opts?.method==="POST"){posts.push(JSON.parse(opts.body));return Response.json(base("hand",{match:match(),queue:{humans:6,required:6}}));}return fetchProfile(base("reserved",{reservation,queue:{humans:6,required:6}}))(url);});
});
test("accepted reservation keeps Agent hand held until all six accept, no simulated human hand",async()=>{
 await harness(({dom})=>{assert.ok(dom.window.document.querySelector('[data-testid="unrated-local-Agent"]'));assert.match(dom.window.document.body.textContent,/Waiting for everyone/);assert.equal(dom.window.document.querySelector(".ff-actions"),null);},fetchProfile(base("reserved",{reservation:{id:"r",expiresAt:NOW+60000,accepted:true,acceptedHumans:5},queue:{humans:6,required:6}})));
});
test("uncertain human action retains exact body, locks Exit, and signout drops late replies",async()=>{
 const posts=[];let resolve;await harness(async({dom,click,root,props,updates})=>{await click("Fold");assert.match(dom.window.document.body.textContent,/Not confirmed/);assert.ok(dom.window.document.querySelector(".ff-exit").disabled);await click("Retry");assert.equal(posts[0],posts[1]);await act(async()=>root.render(React.createElement(HumanRankArena,{...props,ready:false})));const count=updates.length;await act(async()=>resolve(Response.json(base("queued"))));assert.equal(updates.length,count);assert.equal(dom.window.document.querySelector(".agent-felt"),null);},async(url,opts)=>{if(url.endsWith("/action")){posts.push(opts.body);if(posts.length===1)throw Error("network");return new Promise(r=>resolve=r);}return fetchProfile(base("hand",{match:match()}))(url);});
});
test("seat and side avatars request public profile only, expose unknown samples, restore focus and close with Escape",async()=>{
 const urls=[];await harness(async({dom})=>{const trigger=dom.window.document.querySelector(".agent-profile-trigger");trigger.focus();await act(async()=>trigger.click());assert.match(dom.window.document.querySelector('[role="dialog"]').textContent,/Unknown · insufficient samples/);assert.match(dom.window.document.querySelector('[role="dialog"]').textContent,/Only server-public samples/);await act(async()=>window.dispatchEvent(new window.KeyboardEvent("keydown",{key:"Escape"})));assert.equal(dom.window.document.querySelector('[role="dialog"]'),null);assert.equal(dom.window.document.activeElement,trigger);await act(async()=>dom.window.document.querySelector(".agent-mini-profile").click());assert.ok(dom.window.document.querySelector('[role="dialog"]'));},async url=>{urls.push(url);if(url.includes("/opponent?")){const id=new URL(url).searchParams.get("player");return Response.json({season:"human-fastfold-v1",player:{id,name:"Public Player",style:"unknown",hands:2,rating:1000,stats:{hands:2,vpip:{percent:50},pfr:{percent:null}},confidence:"insufficient"}});}return fetchProfile(base("hand",{match:match()}))(url);});assert.equal(urls.filter(url=>url.includes("/opponent?")).length,2);
});
test("human Exit folds only own hand and fixed break resumes into queue, not same hand",async()=>{
 const posts=[];await harness(async({dom,root,props,nav,click})=>{await click("Exit");assert.equal(nav.at(-1),"waiting");assert.match(dom.window.document.body.textContent,/not the old hand/);assert.equal(dom.window.document.querySelector(".ff-countdown").textContent,"15:00");await act(async()=>root.render(React.createElement(HumanRankArena,{...props,view:"waiting"})));await click("Resume");assert.equal(nav.at(-1),"play");assert.ok(dom.window.document.querySelector('[data-testid="unrated-local-Agent"]'));assert.equal(dom.window.document.querySelector(".agent-felt"),null);},async(url,opts)=>{if(opts?.method==="POST"){posts.push(url);return Response.json(url.endsWith("/break")?base("break",{version:1,breakExpiresAt:NOW+900000}):base("queued",{version:2}));}return fetchProfile(base("hand",{match:match()}))(url);});assert.ok(posts[0].endsWith("/break"));assert.ok(posts[1].endsWith("/resume"));
});
test("expired human break confirms server out before list; browser skew cannot award or extend ranking",async()=>{
 let reads=0;const oldNow=Date.now;Date.now=()=>NOW+86400000;try{await harness(({dom,nav})=>{assert.equal(nav.at(-1),"library");assert.equal(dom.window.document.querySelector(".agent-felt"),null);},async url=>{if(url.endsWith("/status"))return Response.json({enabled:true,season:"human-fastfold-v1",mode:"six_verified_humans",requiredHumans:6,comparisonMode:"shadow",appliedPenalty:false});reads++;return Response.json(reads===1?base("break",{breakExpiresAt:NOW}):base("out",{version:1}));},true,"waiting");}finally{Date.now=oldNow;}
});

test("human waiting/profile regressions are registered in scoped CI and seated users renew their lease",async()=>{
 const {readFile}=await import("node:fs/promises");const workflow=await readFile(new URL("../../../.github/workflows/verify-fastfold.yml",import.meta.url),"utf8");assert.match(workflow,/apps\/frontend\/tests\/human-ranked-ui\.test\.mjs/);assert.match(workflow,/--test tests\/human-ranked-ui\.test\.mjs tests\/poker-table-ui\.test\.mjs/);const source=await readFile(new URL("../src/trainer/HumanRankArena.tsx",import.meta.url),"utf8");assert.match(source,/\["queued","reserved","hand"\]\.includes\(s.phase\)/);
});

test("seated player heartbeat renews player lease without changing the hand-action version",async()=>{
 const timers=[],posts=[];const initial=base("hand",{version:9,match:match()});await harness(async({dom,updates})=>{assert.equal(dom.window.document.querySelector(".ff-actions")!==null,true);const heartbeat=timers.find(t=>t.ms===15000);assert.ok(heartbeat);await act(async()=>{heartbeat.fn();await Promise.resolve();});assert.equal(posts.length,1);assert.equal(posts[0].version,9);assert.ok(posts[0].actionId);assert.equal(updates.at(-1).state.hands,0);assert.equal(dom.window.document.querySelectorAll(".agent-seat").length,6);},async(url,opts)=>{if(url.endsWith("/heartbeat")){posts.push(JSON.parse(opts.body));return Response.json(base("hand",{version:10,match:match(),leaseExpiresAt:NOW+60000}));}return fetchProfile(initial)(url);},true,"play",dom=>{dom.window.setInterval=(fn,ms)=>{timers.push({fn,ms});return timers.length;};dom.window.clearInterval=()=>{};});
});
