// SQL for the canonical local postflop artifacts in the reysonai D1 database (schema:
// apps/backend/migrations). Spots whose flop policy or report is missing or stale are
// skipped. Run through scripts/publish-d1.mjs.
import { createHash } from "node:crypto";
import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { artifactPaths, config, loadInputs, readArtifact, root } from "./inputs.mjs";
import { loadCandidate, loadLaterCandidate } from "./generate.mjs";
import { generationInputOptions } from "./generation-options.mjs";
import { PROFILE_IDS, POLICY_ROLES } from "./generate-profiles.mjs";
import { profileArtifactKey, resolveFlopCandidate, resolveLaterCandidate } from "./candidate-source.ts";
import { SIMULATION_VERSION } from "./simulation.mjs";
import { POSTFLOP_SPOTS } from "./spots.ts";

// D1 rejects SQL statements over 100 KB, so every stored JSON value must stay below this.
export const MAX_VALUE_BYTES = 90_000;
export const quote = value => `'${String(value).replaceAll("'", "''")}'`;
const sha = value => createHash("sha256").update(value).digest("hex");

function jsonValue(value, label) {
  const text = JSON.stringify(value);
  if (Buffer.byteLength(text) > MAX_VALUE_BYTES) throw new Error(`${label} is ${Buffer.byteLength(text)} bytes, over the ${MAX_VALUE_BYTES}-byte D1 statement budget`);
  return quote(text);
}

// Artifacts of one spot, or null with a reason when it is not publishable.
export function spotArtifacts(spot) {
  if (!spot.reachable) return { skip: "unreachable" };
  let inputs, candidate, laterCandidate;
  try {
    inputs = loadInputs(spot.id);
    candidate = loadCandidate(inputs);
    laterCandidate = loadLaterCandidate(inputs, candidate);
  } catch (error) { return { skip: error.message }; }
  const report = readArtifact(spot, "report");
  if (!report || report.policy_hash !== candidate.metadata.policy_hash || report.source_hash !== inputs.fingerprint ||
      report.simulation_version !== SIMULATION_VERSION) return { skip: "report missing or stale" };
  return { spot, candidate, laterCandidate, report };
}

export function buildSql(published, publishedAt = new Date().toISOString(), profiles = []) {
  const lines = ["-- Generated by apps/frontend/scripts/postflop-ai/publish-d1.mjs. Replaces every postflop row.",
    "DELETE FROM postflop_policies;", "DELETE FROM postflop_reports;",
    "DELETE FROM postflop_reasons;", "DELETE FROM postflop_spots;", "DELETE FROM postflop_profile_policies;"];
  for (const { spot, candidate, laterCandidate, report } of published) {
    const id = quote(spot.id);
    lines.push(`INSERT INTO postflop_spots (spot_id, slug, kind, tree, ip, oop, pot_bb, stack_bb, spot_json) VALUES (${id}, ${quote(spot.slug)}, ${quote(spot.kind)}, ${quote(spot.tree)}, ${quote(spot.ip)}, ${quote(spot.oop)}, ${Number(spot.potBb)}, ${Number(spot.stackBb ?? 100)}, ${jsonValue(spot, `${spot.id} spot`)});`);
    for (const [stage, item] of [["flop", candidate], ["later", laterCandidate]]) {
      if (!item) continue;
      lines.push(`INSERT INTO postflop_policies (spot_id, stage, policy_hash, metadata_json, policy_json) VALUES (${id}, '${stage}', ${quote(item.metadata.policy_hash)}, ${jsonValue(item.metadata, `${spot.id} ${stage} metadata`)}, ${jsonValue(item, `${spot.id} ${stage} policy`)});`);
    }
    lines.push(`INSERT INTO postflop_reports (spot_id, payload_json) VALUES (${id}, ${jsonValue(report, `${spot.id} report`)});`);
  }
  const hashes = Object.fromEntries(published.map(({ spot, candidate, laterCandidate }) =>
    [spot.id, { flop: candidate.metadata.policy_hash, later: laterCandidate?.metadata.policy_hash ?? null }]));
  const profileHashes = {};
  for (const { profile, spot, flop, later } of profiles) {
    profileHashes[profile] ??= {};
    const roles = profileHashes[profile][spot.id] = {};
    for (const role of POLICY_ROLES) {
      roles[role] = {};
      for (const [stage, candidate] of [["flop", flop[role]], ["later", later[role]]]) {
        const label = `${profile}/${spot.id}/${role}/${stage}`;
        roles[role][stage] = { policy: candidate.metadata.policy_hash, metadata: sha(JSON.stringify(candidate.metadata)) };
        lines.push(`INSERT INTO postflop_profile_policies (profile, spot_id, role, stage, metadata_json, policy_json, published_at) VALUES (${quote(profile)}, ${quote(spot.id)}, ${quote(role)}, ${quote(stage)}, ${jsonValue(candidate.metadata, `${label} metadata`)}, ${jsonValue(candidate.policy, `${label} policy`)}, ${quote(publishedAt)});`);
      }
    }
  }
  const profileDetail = { kind: "ai_estimate_not_gto", profiles: Object.fromEntries(PROFILE_IDS.map(profile =>
    [profile, { spots: Object.keys(profileHashes[profile] ?? {}).length, policies: Object.keys(profileHashes[profile] ?? {}).length * 4 }])), policies: profiles.length * 4 };
  const contentHash = sha(JSON.stringify({ spots: hashes, profiles: profileHashes }));
  lines.push("DELETE FROM dataset_versions WHERE name = 'postflop';");
  lines.push(`INSERT INTO dataset_versions (name, content_hash, published_at, detail_json) VALUES ('postflop', ${quote(contentHash)}, ${quote(publishedAt)}, ${jsonValue({ spots: hashes, profilePolicies: profiles.length * 4 }, "dataset detail")});`);
  lines.push("DELETE FROM dataset_versions WHERE name = 'postflop-profiles';");
  lines.push(`INSERT INTO dataset_versions (name, content_hash, published_at, detail_json) VALUES ('postflop-profiles', ${quote(sha(JSON.stringify(profileHashes)))}, ${quote(publishedAt)}, ${jsonValue(profileDetail, "profile dataset detail")});`);
  return `${lines.join("\n")}\n`;
}

// Every publishable spot, logging what is skipped and why.
// requireAll (CI): every reachable spot must publish with its turn/river policy, because the
// SQL replaces every postflop row and a skipped spot would vanish from production.
export function publishableSpots(log = console.log, { requireAll = false } = {}) {
  const published = [];
  for (const spot of POSTFLOP_SPOTS) {
    const result = spotArtifacts(spot);
    if (result.skip) {
      if (requireAll && result.skip !== "unreachable") throw new Error(`${spot.id} is not publishable: ${result.skip}`);
      log(`skip ${spot.id}: ${result.skip}`); continue;
    }
    if (requireAll && !result.laterCandidate) throw new Error(`${spot.id} has no turn/river policy`);
    published.push(result);
    log(`publish ${spot.id}${result.laterCandidate ? " +later" : ""}`);
  }
  return published;
}

// Each generated profile/spot is an indivisible four-file delivery unit. Fully
// absent HU-after-multiway units are still preparing; any present partial/stale
// unit is a hard failure before producing the destructive replacement SQL.
export function publishableProfiles(log = console.log, { requireAll = false, spots = POSTFLOP_SPOTS,
  read = readArtifact, inputsFor = loadInputs } = {}) {
  const published = [];
  if (read === readArtifact) for (const profile of PROFILE_IDS) {
    const expected = new Set(spots.flatMap(spot => POLICY_ROLES.flatMap(role => ["candidate", "laterCandidate"].map(kind =>
      `${profileArtifactKey(spot, kind, profile, role).split("/").at(-1)}.json`))));
    for (const base of ["scripts/data/postflop-ai/profiles", ".local/postflop-ai/profiles"]) {
      const directory = join(root, base, profile);
      if (!existsSync(directory)) continue;
      for (const name of readdirSync(directory)) if (name.endsWith(".json") && !expected.has(name)) {
        throw new Error(`${profile}/${name}: unknown generated profile artifact`);
      }
    }
  }
  for (const profile of PROFILE_IDS) for (const spot of spots) {
    const flop = {}, later = {};
    try {
      let present = 0;
      for (const role of POLICY_ROLES) for (const [kind, pair] of [["candidate", flop], ["laterCandidate", later]]) {
        pair[role] = read(spot, kind, { profile, role });
        // JSON null/false is an invalid present file, not an ungenerated unit.
        const onDisk = read === readArtifact && (existsSync(artifactPaths(spot, { profile, role })[kind]) ||
          existsSync(join(root, ".local/postflop-ai", `${profileArtifactKey(spot, kind, profile, role)}.json`)));
        if (onDisk || pair[role] !== null && pair[role] !== undefined) present++;
      }
      if (!present && "history" in spot) { log(`skip ${profile}/${spot.id}: profile policy is not generated`); continue; }
      if (present && present !== 4) throw new Error(`Incomplete generated profile policy: ${present}/4 files`);
      let inputs;
      try { inputs = inputsFor(spot.id, generationInputOptions(spot.id, profile)); }
      catch (error) {
        if (!present && /unreachable after range adjustment/.test(error.message)) {
          log(`skip ${profile}/${spot.id}: unreachable adjusted history`); continue;
        }
        throw error;
      }
      if (!present && !requireAll) { log(`skip ${profile}/${spot.id}: profile policy is not generated`); continue; }
      if (present !== 4) throw new Error(`Incomplete generated profile policy: ${present}/4 files`);
      for (const role of POLICY_ROLES) for (const [stage, candidate] of [["flop", flop[role]], ["later", later[role]]]) {
        const metadata = candidate?.metadata;
        if (metadata?.profile !== profile || metadata?.role !== role || metadata?.spot !== spot.id ||
            metadata?.structure_hash !== inputs.structure_hash || metadata?.config_version !== config.version ||
            candidate?.profileCandidates || metadata?.kind !== "ai_estimate_not_gto" ||
            (stage === "flop" ? metadata?.tree !== spot.tree : metadata?.tree !== undefined && metadata.tree !== spot.tree)) {
          throw new Error(`Profile policy identity mismatch: ${stage}/${role}`);
        }
      }
      const resolved = resolveFlopCandidate(inputs, flop);
      resolveLaterCandidate(inputs, later, resolved);
      published.push({ profile, spot, flop, later });
      log(`publish ${profile}/${spot.id}: villain+exploit flop+later`);
    } catch (error) { throw new Error(`${profile}/${spot.id} is not publishable: ${error.message}`, { cause: error }); }
  }
  return published;
}
