// SQL for the canonical local postflop artifacts in the evionai D1 database (schema:
// apps/backend/migrations). Spots whose flop policy or report is missing or stale are
// skipped. Run through scripts/publish-d1.mjs.
import { createHash } from "node:crypto";
import { loadInputs, readArtifact } from "./inputs.mjs";
import { loadCandidate, loadLaterCandidate } from "./generate.mjs";
import { loadHandEv } from "./hand-ev.mjs";
import { SIMULATION_VERSION } from "./simulation.mjs";
import { POSTFLOP_SPOTS } from "./spots.mjs";

// D1 rejects SQL statements over 100 KB, so every stored JSON value must stay below this.
export const MAX_VALUE_BYTES = 90_000;
export const quote = value => `'${String(value).replaceAll("'", "''")}'`;
const sha = value => createHash("sha256").update(value).digest("hex");

function jsonValue(value, label) {
  const text = JSON.stringify(value);
  if (Buffer.byteLength(text) > MAX_VALUE_BYTES) throw new Error(`${label} is ${Buffer.byteLength(text)} bytes, over the ${MAX_VALUE_BYTES}-byte D1 statement budget`);
  return quote(text);
}

// Hand-EV files are too large for one row: the header is stored at ('', ''), and each node
// at (board, history) for the flop file ({boards: {board: {history: node}}}) or at (key, '*')
// for a turn/river file ({boards: {key: node}}). The edge worker reassembles the file.
// Turn/river hand-EV is not published: it is computed per hand on demand (~150MB per spot).
export function handEvRows(data, stage) {
  const { boards, ...header } = data;
  const rows = [{ board_key: "", history: "", payload: header }];
  for (const [board, value] of Object.entries(boards)) {
    if (stage === "flop") for (const [history, node] of Object.entries(value)) rows.push({ board_key: board, history, payload: node });
    else rows.push({ board_key: board, history: "*", payload: value });
  }
  return rows;
}

// Artifacts of one spot, or null with a reason when it is not publishable.
export function spotArtifacts(spot) {
  if (!spot.reachable) return { skip: "unreachable" };
  let inputs, candidate, laterCandidate;
  try {
    inputs = loadInputs(spot.id);
    candidate = loadCandidate(inputs);
    laterCandidate = loadLaterCandidate(inputs, candidate);
  } catch (error) { return { skip: error.message }; }
  const report = readArtifact(spot, "report");
  if (!report || report.policy_hash !== candidate.metadata.policy_hash || report.source_hash !== inputs.fingerprint ||
      report.simulation_version !== SIMULATION_VERSION) return { skip: "report missing or stale" };
  // Only hand-EV computed from these policies with the current defence model is published; the worker
  // serves stored rows as they are, and the app computes missing boards on demand.
  return { spot, candidate, laterCandidate, report, handEv: loadHandEv(inputs, candidate, laterCandidate) };
}

export function buildSql(published, publishedAt = new Date().toISOString()) {
  const lines = ["-- Generated by apps/frontend/scripts/postflop-ai/publish-d1.mjs. Replaces every postflop row.",
    "DELETE FROM postflop_hand_ev;", "DELETE FROM postflop_policies;", "DELETE FROM postflop_reports;",
    "DELETE FROM postflop_reasons;", "DELETE FROM postflop_spots;"];
  for (const { spot, candidate, laterCandidate, report, handEv } of published) {
    const id = quote(spot.id);
    lines.push(`INSERT INTO postflop_spots (spot_id, slug, kind, tree, ip, oop, pot_bb, stack_bb, spot_json) VALUES (${id}, ${quote(spot.slug)}, ${quote(spot.kind)}, ${quote(spot.tree)}, ${quote(spot.ip)}, ${quote(spot.oop)}, ${Number(spot.potBb)}, ${Number(spot.stackBb ?? 100)}, ${jsonValue(spot, `${spot.id} spot`)});`);
    for (const [stage, item] of [["flop", candidate], ["later", laterCandidate]]) {
      if (!item) continue;
      lines.push(`INSERT INTO postflop_policies (spot_id, stage, policy_hash, metadata_json, policy_json) VALUES (${id}, '${stage}', ${quote(item.metadata.policy_hash)}, ${jsonValue(item.metadata, `${spot.id} ${stage} metadata`)}, ${jsonValue(item, `${spot.id} ${stage} policy`)});`);
    }
    lines.push(`INSERT INTO postflop_reports (spot_id, payload_json) VALUES (${id}, ${jsonValue(report, `${spot.id} report`)});`);
    for (const row of handEv ? handEvRows(handEv, "flop") : []) {
      lines.push(`INSERT INTO postflop_hand_ev (spot_id, stage, board_key, history, payload_json) VALUES (${id}, 'flop', ${quote(row.board_key)}, ${quote(row.history)}, ${jsonValue(row.payload, `${spot.id} flop hand-EV ${row.board_key}/${row.history}`)});`);
    }
  }
  const hashes = Object.fromEntries(published.map(({ spot, candidate, laterCandidate }) =>
    [spot.id, { flop: candidate.metadata.policy_hash, later: laterCandidate?.metadata.policy_hash ?? null }]));
  lines.push("DELETE FROM dataset_versions WHERE name = 'postflop';");
  lines.push(`INSERT INTO dataset_versions (name, content_hash, published_at, detail_json) VALUES ('postflop', ${quote(sha(JSON.stringify(hashes)))}, ${quote(publishedAt)}, ${jsonValue({ spots: hashes }, "dataset detail")});`);
  return `${lines.join("\n")}\n`;
}

// Every publishable spot, logging what is skipped and why.
export function publishableSpots(log = console.log) {
  const published = [];
  for (const spot of POSTFLOP_SPOTS) {
    const result = spotArtifacts(spot);
    if (result.skip) { log(`skip ${spot.id}: ${result.skip}`); continue; }
    published.push(result);
    log(`publish ${spot.id}${result.laterCandidate ? " +later" : ""}${result.handEv ? " +hand-ev" : ""}`);
  }
  return published;
}
