import type pilotConfig from "../data/postflop-ai-pilot.json";
import type { TableProfile } from "../../src/estimated/table-profile.ts";
import type { BettingStep, FlopTree, PlayerRole } from "./tree.ts";
import type { LaterStreet } from "./later-tree.ts";
import type { Spot } from "./spots.ts";
import type { WeightedCombo } from "../lib/equity.ts";

export type Position = "UTG" | "HJ" | "CO" | "BTN" | "SB" | "BB";
export type PilotConfig = typeof pilotConfig;
export type Street = "flop" | LaterStreet;
export type HandTier = "monster" | "strong" | "draw" | "medium" | "air";
export type BoardShape = "dry" | "wet" | "monotone" | "paired";
export type BoardHeight = "high" | "mid" | "low";
export type FlopTexture = BoardShape | BoardHeight | `${BoardShape}_${BoardHeight}`;
export type RunoutTexture = "blank" | "over" | "pair" | "straight" | "flush";
export type PreviousLine = "aggressor" | "defender" | "checked";
export type OpponentProfile = "standard" | "passive" | "aggressive";
export type ActionMix = Record<string, number>;
export type FlopRule = { node: string; texture: FlopTexture | "any"; tier: HandTier; mix: ActionMix };
export type FlopPolicy = { version: 1; kind: "ai_estimate_not_gto"; rules: FlopRule[] };
export type LaterRule = { node: string; line: PreviousLine | "any"; texture: RunoutTexture | "any"; tier: HandTier; mix: ActionMix };
export type LaterPolicy = { version: 1; kind: "ai_estimate_not_gto"; streets: Record<LaterStreet, { rules: LaterRule[] }> };
export type FrequencyRow = { hand: string; freq: number };
export type SourceAction = "open" | "call" | "fold" | "three_bet" | "four_bet" | "limp" | "check" | "raise" | "squeeze" | "all_in";
export type SourceHand = { hand: string; three_bet_size_bb?: number | null; four_bet_size_bb?: number | null; limp_size_bb?: number | null } & Record<SourceAction, number>;
export type SourceSpot = { id: string; hands: SourceHand[]; hero: Position; opener: Position; three_bettor: Position;
  open_size_bb: number; effective_stack_bb: number; three_bet_size_bb: number; four_bet_size_bb: number;
  raise_size_bb: number; iso_size_bb: number; raise_to_bb: number; limp_reraise_size_bb: number;
  source_response_id: string; source_three_bet_response_id: string };
export type SourceDataset = { spots: SourceSpot[] };
export type MultiwaySpot = { id: string; kind: "sqp" | "ccp" | "c4bp"; opener: Position; caller: Position; aggressor: Position;
  ip: Position; oop: Position; tree: FlopTree; openingId: string; responseId: string; openBb: number; potBb: number; stackBb: number;
  slug: string; reachable: boolean; stage: "A" | "B"; terminalId: string;
  history: { seat: Position; action: SourceAction; to_size_bb: number | null }[];
  contributionsBb: Record<Position, number>; ranges: Record<string, RangeFactor[]>;
  reach: { probability: number; samples: number; compatible_samples: number; method: string } };
export type MultiwayCatalog = { version: number; structural: number; reachable: number; stageA: number; stageB: number;
  spots: MultiwaySpot[]; deferred: { id: string; terminalId: string; reach: MultiwaySpot["reach"]; reason: string }[];
  omitted: { id: string; terminalId: string; reason: string }[] };
// Profile datasets use the same flat path keys as their persisted files, without .json:
// profiles/<profile>/villain/<dataset>. No standard-range fallback is allowed.
export type PostflopDatasets = Record<string, SourceDataset | MultiwayCatalog | undefined>;
export type InputOpponentProfile = "standard" | "nit" | "station" | "lag" | "maniac";
export type InputOptions = { tableProfile?: Partial<TableProfile>; opponentProfile?: InputOpponentProfile; opponentSeat?: PlayerRole };
export type InputAdjustment = { tableProfile: TableProfile; opponentProfile: InputOpponentProfile };
export type RangeFactor = readonly [file: string, spotId: string, action: SourceAction];
export type Inputs = { spot: Spot; opening?: SourceSpot; response?: SourceSpot; sources?: { dataset: string; spot: SourceSpot }[]; threeBet?: SourceSpot; threeBetResponse?: SourceSpot;
  config: PilotConfig; fingerprint: string; structure_hash: string; baselineFingerprint?: string; adjusted?: InputAdjustment;
  tableProfile?: TableProfile; opponentProfile?: InputOpponentProfile; opponentSeat?: PlayerRole; seatRows: Record<string, FrequencyRow[]> };
export type ReachStep = BettingStep & { canRaise?: boolean };
export type StrategyCombo = { cards: string; tier: HandTier; weight: number; reachWeight?: number; mix: ActionMix };
export type StrategyRow = { hand: string; comboCount: number; reachable: boolean; mix: ActionMix; tiers: Record<HandTier, number>; combos: StrategyCombo[]; reachWeight: number; tier?: string };
export type StrategyNode = { node?: string; seat: string; actions: readonly string[]; rows: StrategyRow[] };
export type StrategyNodes = Record<string, StrategyNode>;
export type Candidate<P = FlopPolicy> = { policy: P; metadata: { source_hash: string; policy_hash: string; flop_policy_hash?: string; [key: string]: unknown } };
export type WeightedRange = WeightedCombo[];
export type RoleValues = Record<PlayerRole, number>;
export type SpotTree = FlopTree;
